bake using just the CSS file and disable validation

diff --git a/script/bake-book b/script/bake-book
--- a/script/bake-book
+++ b/script/bake-book
@@ -55,7 +55,7 @@ for book_config in "${BOOK_CONFIGS[@]}"; do
   css_file="./recipes/output/${recipe_name}.css"
   lcov_file="${baked_file}.lcov"
 
-  [[ -f "${raw_file}" ]] || die "Could not find the raw HTML file. Have you run fetch-html yet?"
+  [[ -f "${raw_file}" ]] || die "Could not find the raw HTML file at ${raw_file}. Have you run fetch-html yet?"
 
   [[ -f "${sass_file}" ]] || die "Could not find the raw SCSS file at ${sass_file}"
 
@@ -63,8 +63,8 @@ for book_config in "${BOOK_CONFIGS[@]}"; do
   [[ ! -f "${baked_file}" ]] || rm "${baked_file}"
 
   # shellcheck disable=SC2086
-  do_progress_quiet "Baking ${raw_file} using ${recipe_name} (~1min)" \
-    "$(npm bin)/css-plus" ${debug_flag1} ${debug_flag2} ${debug_flag3} ${debug_flag4} --css "${css_file}" --html "${raw_file}" --output "${baked_file}"
+  do_progress "Baking ${raw_file} using ${recipe_name} (~1min)"
+  try "$(npm bin)/css-plus" --nocssmap ${debug_flag1} ${debug_flag2} ${debug_flag3} ${debug_flag4} --css "${css_file}" --html "${raw_file}" --output "${baked_file}"
 
   # Generate an HTML report (if genhtml is installed)
   if [[ -n "$(which genhtml)" ]]; then
@@ -72,7 +72,7 @@ for book_config in "${BOOK_CONFIGS[@]}"; do
       genhtml --quiet --output ./coverage/ "${lcov_file}"
   fi
 
-  # Validate the cooked file
-  do_progress_quiet "Validating ${baked_file}" \
-    cnx-epub-validate-collated "${baked_file}"
+  # # Validate the cooked file
+  # do_progress_quiet "Validating ${baked_file}" \
+  #   cnx-epub-validate-collated "${baked_file}"
 done
