:art: clean scripts to use bootstrap

diff --git a/script/bake-book b/script/bake-book
--- a/script/bake-book
+++ b/script/bake-book
@@ -1,6 +1,8 @@
 #!/bin/bash
-set -e
 
+cd "$(dirname "$0")/.."
+
+source ./script/bootstrap || exit 1
 
 arg1=$1
 debugFlag1=$2
@@ -10,93 +12,68 @@ debugFlag4=$5
 
 # Check command line args
 
-if [ -z "${arg1}" ]
-then
-  >&2 echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument (or --all). For example: physics'
-  >&2 echo "You can specify additional commandline arguments like -d to this script if you want more debugging"
-  exit 1
+if [ -z "${arg1}" ]; then
+  _say 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument (or --all). For example: physics'
+  _say "You can specify additional commandline arguments like -d to this script if you want more debugging"
+  die "Stopping because no commandline args were passed in"
 fi
 
 
 # Pull in the BOOK_CONFIGS
 source ./books.txt || exit 1
 
-if [ ! "${arg1}" == "--all" ]
-then
+if [ ! "${arg1}" == "--all" ]; then
   # Filter BOOK_CONFIGS to only contain the book you want to fetch
-  for bookConfig in "${BOOK_CONFIGS[@]}"
-  do
+  for bookConfig in "${BOOK_CONFIGS[@]}"; do
     read -r bookConfigName recipeName uuid _ <<< "${bookConfig}"
 
-    if [[ "${arg1}" = "${bookConfigName}" ]]
-    then
+    if [[ "${arg1}" = "${bookConfigName}" ]]; then
       BOOK_CONFIGS=("${bookConfigName} ${recipeName} ${uuid}")
       foundConfig=1
       break
     fi
   done
 
-  if [[ ! 1 -eq "${foundConfig}" ]]
-  then
-    >&2 echo "ERROR: Could not find Book info for book named ${arg1}"
-    >&2 echo "Valid books are (from ./books.txt):"
-    for bookConfig in "${BOOK_CONFIGS[@]}"
-    do
+  if [[ ! 1 -eq "${foundConfig}" ]]; then
+    _say "Valid books are (from ./books.txt):"
+    for bookConfig in "${BOOK_CONFIGS[@]}"; do
       read -r bookName recipeName uuid _ <<< "${bookConfig}"
-      >&2 echo "${bookName}"
+      _say "${bookName}"
     done
-    exit 1
+    die "Could not find Book info for book named ${arg1}"
   fi
 fi
 
 
-for bookConfig in "${BOOK_CONFIGS[@]}"
-do
+for bookConfig in "${BOOK_CONFIGS[@]}"; do
   read -r bookName recipeName uuid _ <<< "${bookConfig}"
 
-  ./script/compile-books ${recipeName} || exit 1
+  do_progress_quiet "Compiling CSS file" \
+    ./script/compile-books ${recipeName}
 
   rawFile="./data/${bookName}-raw.xhtml"
   bakedFile="./data/${bookName}-baked.xhtml"
   sassFile="./recipes/books/${recipeName}/book.scss"
   cssFile="./recipes/output/${recipeName}.css"
-
-  if [ ! -f "${rawFile}" ]
-  then
-    >&2 echo 'ERROR: Could not find the raw HTML file. Have you run fetch-html yet?'
-    exit 1
-  fi
-
-  if [ ! -f "${sassFile}" ]
-  then
-    >&2 echo "ERROR: Could not find the raw SCSS file at ${sassFile}"
-    exit 1
-  fi
-
-
-  >&2 echo "==> Baking ${rawFile} using ${recipeName} (may take a few minutes)"
-
-  # Remove the baked file if it exists
-  [ -e "${bakedFile}" ] && rm ${bakedFile}
-
-  # Activate the venv if not already in a virtualenv
-  if [[ -z "${VIRTUAL_ENV}" ]]
-  then
-    source ./venv/bin/activate
-  fi
-
   lcovFile="${rawFile}.lcov"
 
-  cnx-easybake --coverage-file "${lcovFile}" ${debugFlag1} ${debugFlag2} ${debugFlag3} ${debugFlag4} "${cssFile}" "${rawFile}" "${bakedFile}"
+  [[ -f "${rawFile}" ]] || die "Could not find the raw HTML file. Have you run fetch-html yet?"
+
+  [[ -f "${sassFile}" ]] || die "Could not find the raw SCSS file at ${sassFile}"
+
+  # Remove the baked file if it exists
+  [[ ! -f "${bakedFile}" ]] || rm ${bakedFile}
+
+  do_progress_quiet "Baking ${rawFile} using ${recipeName} (~1min)" \
+    cnx-easybake --coverage-file "${lcovFile}" ${debugFlag1} ${debugFlag2} ${debugFlag3} ${debugFlag4} "${cssFile}" "${rawFile}" "${bakedFile}"
 
   # Generate an HTML report (if genhtml is installed)
-  if [[ -n "$(which genhtml)" ]]
-  then
-    >&2 echo "==> Generating HTML coverage report at ./coverage/"
-    genhtml --quiet --output ./coverage/ "${lcovFile}"
+  if [[ -n "$(which genhtml)" ]]; then
+    do_progress_quiet "Generating HTML coverage report at ./coverage/" \
+      genhtml --quiet --output ./coverage/ "${lcovFile}"
   fi
 
   # Validate the cooked file
-  >&2 echo "==> Validating ${bakedFile}"
-  cnx-epub-validate-collated ${bakedFile}
+  do_progress_quiet "Validating ${bakedFile}" \
+    cnx-epub-validate-collated ${bakedFile}
 done
diff --git a/script/bake-file b/script/bake-file
--- a/script/bake-file
+++ b/script/bake-file
@@ -1,5 +1,9 @@
 #!/bin/bash
-set -e
+
+cd "$(dirname "$0")/.."
+
+source ./script/bootstrap || exit 1
+
 
 bookName=$1
 rawFile=$2
@@ -11,45 +15,24 @@ cssFile="./recipes/output/${bookName}.css"
 
 # Check command line args
 
-if [ -z "${bookName}" ]
-then
-  echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'
-  echo 'The required arguments are: bookName, rawFile, bakedFile'
-  exit 1
-fi
+[[ "${bookName}" ]] || die 'Argument Missing. You must specify the name of the book as the 1st argument. For example: physics. The required arguments are: bookName, rawFile, bakedFile'
 
-if [ ! -f "${rawFile}" ]
-then
-  echo "ERROR: Could not find the raw HTML file at ${rawFile}"
-  exit 1
-fi
+[[ -f "${rawFile}" ]] || die "Could not find the raw HTML file at ${rawFile}"
 
-if [ -z "${bakedFile}" ]
-then
-  echo 'ERROR: You must specify a baked path'
-  exit 1
-fi
+[[ "${bakedFile}" ]] || die 'You must specify a baked path'
 
-if [ ! -f "${sassFile}" ]
-then
-  echo "ERROR: Could not find the raw SCSS file at ${sassFile}"
-  exit 1
-fi
+[[ -f "${sassFile}" ]] || die "Could not find the raw SCSS file at ${sassFile}"
 
 
 # Remove the baked file if it exists
 # [ -e "${bakedFile}" ] && rm ${bakedFile}
 # commented out because it could be /dev/stdout
 
-# Activate the venv if not already in a virtualenv
-if [[ -z "${VIRTUAL_ENV}" ]]
-then
-  source ./venv/bin/activate
-fi
-
 lcovFile="${rawFile}.lcov"
 
-cnx-easybake --coverage-file "${lcovFile}" ${debugFlag} "${cssFile}" "${rawFile}" "${bakedFile}"
+do_progress_quiet "Baking file" \
+  cnx-easybake --coverage-file "${lcovFile}" ${debugFlag} "${cssFile}" "${rawFile}" "${bakedFile}"
+
 # Validate the cooked file.
 # Commented because snippets do not pass the data-type="metadata" validation
 # and adding in all those metadata blocks would be cumbersome and distract
diff --git a/script/diff-book b/script/diff-book
--- a/script/diff-book
+++ b/script/diff-book
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+cd "$(dirname "$0")/.."
+
+source ./script/bootstrap || exit 1
 
 arg1=$1
 debugFlag=$2
@@ -9,82 +12,69 @@ source ./books.txt || exit 1
 
 # Check command line args
 
-if [[ -z "${arg1}" ]]
-then
-  >&2 echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument'
-  >&2 echo ' or --all for all books.'
-  >&2 echo ''
-  >&2 echo 'This script bakes the book and then compares to the prepared book'
-  >&2 echo '(done earlier, usually in another branch)'
-  >&2 echo ''
-  >&2 echo "Valid books are (from ./books.txt):"
-  for bookConfig in "${BOOK_CONFIGS[@]}"
-  do
+if [[ -z "${arg1}" ]]; then
+  _say 'This script bakes the book and then compares to the prepared book'
+  _say '(done earlier, usually in another branch)'
+  _say ''
+  _say "Valid books are (from ./books.txt):"
+  for bookConfig in "${BOOK_CONFIGS[@]}"; do
     read -r bookName recipeName uuid _ <<< "${bookConfig}"
-    >&2 echo "${bookName}"
+    _say "${bookName}"
   done
 
-  exit 1
+  die 'Argument Missing. You must specify the name of the book as the 1st argument or --all for all books.'
 fi
 
 
-if [[ ! "${arg1}" == "--all" ]]
-then
+if [[ ! "${arg1}" == "--all" ]]; then
   # Filter BOOK_CONFIGS to only contain the book you want to fetch
-  for bookConfig in "${BOOK_CONFIGS[@]}"
-  do
+  for bookConfig in "${BOOK_CONFIGS[@]}"; do
     read -r bookConfigName recipeName uuid _ <<< "${bookConfig}"
 
-    if [[ "${arg1}" = "${bookConfigName}" ]]
-    then
+    if [[ "${arg1}" = "${bookConfigName}" ]]; then
       BOOK_CONFIGS=("${bookConfigName} ${recipeName} ${uuid}")
       foundConfig=1
       break
     fi
   done
 
-  if [[ ! 1 -eq "${foundConfig}" ]]
-  then
-    >&2 echo "ERROR: Could not find Book info for book named ${arg1}"
-    >&2 echo "Valid books are (from ./books.txt):"
-    for bookConfig in "${BOOK_CONFIGS[@]}"
-    do
+  if [[ ! 1 -eq "${foundConfig}" ]]; then
+    _say "Valid books are (from ./books.txt):"
+    for bookConfig in "${BOOK_CONFIGS[@]}"; do
       read -r bookName recipeName uuid _ <<< "${bookConfig}"
-      >&2 echo "${bookName}"
+      _say "${bookName}"
     done
-    exit 1
+    die "Could not find Book info for book named ${arg1}"
   fi
 fi
 
-for bookConfig in "${BOOK_CONFIGS[@]}"
-do
+for bookConfig in "${BOOK_CONFIGS[@]}"; do
   read -r bookName recipeName uuid _ <<< "${bookConfig}"
   rawFile="./data/${bookName}-raw.xhtml"
 
   bakedFile="./data/${bookName}-baked.xhtml"
   preparedFile="./data/${bookName}-prepared.xhtml"
 
-  if [[ -s "${preparedFile}" ]]
-  then
+  if [[ -s "${preparedFile}" ]]; then
 
-    ./script/bake-book ${bookName} --use-repeatable-ids || exit 1
+    do_progress_quiet "Baking book" \
+      ./script/bake-book ${bookName} --use-repeatable-ids
 
     diffCount=$(diff ${preparedFile} ${bakedFile} | wc -l)
 
-    if [[ 0 -ne "${diffCount}" ]]
-    then
-      >&2 echo "There were ${diffCount} differences found"
-      >&2 echo "To see all of them run the following:"
-      >&2 echo "diff ${preparedFile} ${bakedFile}"
+    if [[ 0 -ne "${diffCount}" ]]; then
+      _say "There were ${diffCount} differences found"
+      _say "To see all of them run the following:"
+      _say "diff ${preparedFile} ${bakedFile}"
       if [[ ! ${DO_ALL} ]]; then
-        exit 1
+        die "Exiting because differences were found"
       fi
     fi
 
   else
 
-    >&2 echo "SKIPPING ${bookName} because the prepared file was not found."
-    >&2 echo "Did you run './script/diff-book-prepare ${bookName}' earlier?"
+    _say "SKIPPING ${bookName} because the prepared file was not found."
+    _say "Did you run './script/diff-book-prepare ${bookName}' earlier?"
   fi
 
 
diff --git a/script/diff-book-prepare b/script/diff-book-prepare
--- a/script/diff-book-prepare
+++ b/script/diff-book-prepare
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+cd "$(dirname "$0")/.."
+
+source ./script/bootstrap || exit 1
 
 arg1=$1
 debugFlag=$2
@@ -9,61 +12,51 @@ source ./books.txt || exit 1
 
 # Check command line args
 
-if [[ -z "${arg1}" ]]
-then
-  >&2 echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument'
-  >&2 echo ' or --all for all books.'
-  >&2 echo 'This script prepares the book to compare against.'
-  >&2 echo 'Typically this step is done in the master branch'
-  >&2 echo 'and then in another branch diff-book is called to see how the HTML changed.'
-  >&2 echo ''
-  >&2 echo "Valid books are (from ./books.txt):"
-  for bookConfig in "${BOOK_CONFIGS[@]}"
-  do
+if [[ -z "${arg1}" ]]; then
+  _say 'This script prepares the book to compare against.'
+  _say 'Typically this step is done in the master branch'
+  _say 'and then in another branch diff-book is called to see how the HTML changed.'
+  _say ''
+  _say "Valid books are (from ./books.txt):"
+  for bookConfig in "${BOOK_CONFIGS[@]}"; do
     read -r bookName recipeName uuid _ <<< "${bookConfig}"
-    >&2 echo "${bookName}"
+    _say "${bookName}"
   done
-  exit 1
+  die 'Argument Missing. You must specify the name of the book as the 1st argument or --all for all books.'
 fi
 
 
-if [[ ! "${arg1}" == "--all" ]]
-then
+if [[ ! "${arg1}" == "--all" ]]; then
   # Filter BOOK_CONFIGS to only contain the book you want to fetch
-  for bookConfig in "${BOOK_CONFIGS[@]}"
-  do
+  for bookConfig in "${BOOK_CONFIGS[@]}"; do
     read -r bookConfigName recipeName uuid _ <<< "${bookConfig}"
 
-    if [[ "${arg1}" = "${bookConfigName}" ]]
-    then
+    if [[ "${arg1}" = "${bookConfigName}" ]]; then
       BOOK_CONFIGS=("${bookConfigName} ${recipeName} ${uuid}")
       foundConfig=1
       break
     fi
   done
 
-  if [[ ! 1 -eq "${foundConfig}" ]]
-  then
-    >&2 echo "ERROR: Could not find Book info for book named ${arg1}"
-    >&2 echo "Valid books are (from ./books.txt):"
-    for bookConfig in "${BOOK_CONFIGS[@]}"
-    do
+  if [[ ! 1 -eq "${foundConfig}" ]]; then
+    _say "Valid books are (from ./books.txt):"
+    for bookConfig in "${BOOK_CONFIGS[@]}"; do
       read -r bookName recipeName uuid _ <<< "${bookConfig}"
-      >&2 echo "${bookName}"
+      _say "${bookName}"
     done
-    exit 1
+    die "Could not find Book info for book named ${arg1}"
   fi
 fi
 
-for bookConfig in "${BOOK_CONFIGS[@]}"
-do
+for bookConfig in "${BOOK_CONFIGS[@]}"; do
   read -r bookName recipeName uuid _ <<< "${bookConfig}"
   rawFile="./data/${bookName}-raw.xhtml"
 
   bakedFile="./data/${bookName}-baked.xhtml"
   preparedFile="./data/${bookName}-prepared.xhtml"
 
-  ./script/bake-book ${bookName} --use-repeatable-ids || exit 1
+  do_progress_quiet "Baking book" \
+    ./script/bake-book ${bookName} --use-repeatable-ids
 
   mv ${bakedFile} ${preparedFile}
 done
diff --git a/script/diff-guide b/script/diff-guide
--- a/script/diff-guide
+++ b/script/diff-guide
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+cd "$(dirname "$0")/.."
+
+source ./script/bootstrap || exit 1
+
 
 arg1=$1
 debugFlag=$2
@@ -9,68 +13,54 @@ source ./books.txt || exit 1
 
 # Check command line args
 
-./script/diff-guide-prepare "${arg1}" "baked"
+do_progress_quiet "Preparing styleguide for diffing" \
+  ./script/diff-guide-prepare "${arg1}" "baked"
 
 
-if [[ ! "${arg1}" == "--all" ]]
-then
+if [[ ! "${arg1}" == "--all" ]]; then
   # Filter BOOK_CONFIGS to only contain the book you want to fetch
-  for recipeName in "${RECIPE_NAMES[@]}"
-  do
+  for recipeName in "${RECIPE_NAMES[@]}"; do
 
-    if [[ "${arg1}" = "${recipeName}" ]]
-    then
+    if [[ "${arg1}" = "${recipeName}" ]]; then
       RECIPE_NAMES=("${recipeName}")
       foundConfig=1
       break
     fi
   done
 
-  if [[ ! 1 -eq "${foundConfig}" ]]
-  then
-    >&2 echo "ERROR: Could not find Book info for recipe named ${arg1}"
-    >&2 echo "Valid books are (from ./books.txt):"
-    for recipeName in "${RECIPE_NAMES[@]}"
-    do
-      >&2 echo "${recipeName}"
+  if [[ ! 1 -eq "${foundConfig}" ]]; then
+    _say "Valid books are (from ./books.txt):"
+    for recipeName in "${RECIPE_NAMES[@]}"; do
+      _say "${recipeName}"
     done
-    exit 1
+    die "Could not find Book info for recipe named ${arg1}"
   fi
 fi
 
 diffFound=0
-for recipeName in "${RECIPE_NAMES[@]}"
-do
+for recipeName in "${RECIPE_NAMES[@]}"; do
 
-  >&2 echo "==> Checking for differences in '${recipeName}'"
+  progress "Checking for differences in '${recipeName}'"
 
-  for bakedFile in $(find ./tmp/${recipeName} -name "*-baked.xhtml")
-  do
+  for bakedFile in $(find ./tmp/${recipeName} -name "*-baked.xhtml"); do
 
     preparedFile="${bakedFile/-baked/-prepared}"
-    if [[ -s "${preparedFile}" ]]
-    then
+    if [[ -s "${preparedFile}" ]]; then
 
       diffCount=$(diff ${preparedFile} ${bakedFile} | wc -l)
 
-      if [[ 0 -ne "${diffCount}" ]]
-      then
-        >&2 echo "ERROR: There were ${diffCount} differences found. To see all of them run the following:"
-        >&2 echo "diff ${preparedFile} ${bakedFile}"
+      if [[ 0 -ne "${diffCount}" ]]; then
+        _say "WARNING: There were ${diffCount} differences found. To see all of them run diff ${preparedFile} ${bakedFile}:"
         diffFound=1
       fi
 
     else
-      >&2 echo "FAILING ${recipeName} because the prepared file '${preparedFile}' was not found."
-      >&2 echo "Did you run './script/diff-guide-prepare ${recipeName}' earlier?"
-      exit 1
+      die "FAILING ${recipeName} because the prepared file '${preparedFile}' was not found. Did you run './script/diff-guide-prepare ${recipeName}' earlier?"
     fi
 
   done
 done
 
-if [[ ! "${diffFound}" -eq "0" ]]
-then
-  >&2 echo "ERROR: There were differences found so failing"
-  exit 1
+if [[ ! "${diffFound}" -eq "0" ]]; then
+  die "There were differences found so failing"
 fi
diff --git a/script/diff-guide-prepare b/script/diff-guide-prepare
--- a/script/diff-guide-prepare
+++ b/script/diff-guide-prepare
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+cd "$(dirname "$0")/.."
+
+source ./script/bootstrap || exit 1
 
 arg1=$1
 bakedOrPreparedSuffix=$2
@@ -9,55 +12,44 @@ source ./books.txt || exit 1
 
 # Check command line args
 
-if [[ -z "${arg1}" ]]
-then
-  >&2 echo 'ERROR: Argument Missing. You must specify the name of the recipe as the 1st argument'
-  >&2 echo ' or --all for all recipes.'
-  >&2 echo 'This script prepares the guide to compare against.'
-  >&2 echo 'Typically this step is done in the master branch'
-  >&2 echo 'and then in another branch diff-guide is called to see how the HTML changed.'
-  >&2 echo ''
-  >&2 echo "Valid recipes are (from ./books.txt):"
-  for recipeName in "${RECIPE_NAMES[@]}"
-  do
-    >&2 echo "${recipeName}"
+if [[ -z "${arg1}" ]]; then
+  _say 'This script prepares the guide to compare against.'
+  _say 'Typically this step is done in the master branch'
+  _say 'and then in another branch diff-guide is called to see how the HTML changed.'
+  _say ''
+  _say "Valid recipes are (from ./books.txt):"
+  for recipeName in "${RECIPE_NAMES[@]}"; do
+    _say "${recipeName}"
   done
-  exit 1
+  die 'Argument Missing. You must specify the name of the recipe as the 1st argument or --all for all recipes.'
 fi
 
-if [[ -z "${bakedOrPreparedSuffix}" ]]
-then
+if [[ -z "${bakedOrPreparedSuffix}" ]]; then
   bakedOrPreparedSuffix="prepared"
 fi
 
 
-if [[ ! "${arg1}" == "--all" ]]
-then
+if [[ ! "${arg1}" == "--all" ]]; then
   # Filter BOOK_CONFIGS to only contain the book you want to fetch
-  for recipeName in "${RECIPE_NAMES[@]}"
-  do
+  for recipeName in "${RECIPE_NAMES[@]}"; do
 
-    if [[ "${arg1}" = "${recipeName}" ]]
-    then
+    if [[ "${arg1}" = "${recipeName}" ]]; then
       RECIPE_NAMES=("${recipeName}")
       foundConfig=1
       break
     fi
   done
 
-  if [[ ! 1 -eq "${foundConfig}" ]]
-  then
-    >&2 echo "ERROR: Could not find Book info for recipe named ${arg1}"
-    >&2 echo "Valid books are (from ./books.txt):"
-    for recipeName in "${RECIPE_NAMES[@]}"
-    do
-      >&2 echo "${recipeName}"
+  if [[ ! 1 -eq "${foundConfig}" ]]; then
+    _say "Valid books are (from ./books.txt):"
+    for recipeName in "${RECIPE_NAMES[@]}"; do
+      _say "${recipeName}"
     done
-    exit 1
+    die "Could not find Book info for recipe named ${arg1}"
   fi
 fi
 
-for recipeName in "${RECIPE_NAMES[@]}"
-do
-  ./script/generate-guide "${recipeName}" "${bakedOrPreparedSuffix}" || exit 1
+for recipeName in "${RECIPE_NAMES[@]}"; do
+  do_progress_quiet "Generating guide for ${recipeName}" \
+    ./script/generate-guide "${recipeName}" "${bakedOrPreparedSuffix}"
 done
diff --git a/script/fetch-html b/script/fetch-html
--- a/script/fetch-html
+++ b/script/fetch-html
@@ -5,34 +5,32 @@ set -e
 
 arg1=$1
 
+cd "$(dirname "$0")/.."
+
+source ./script/bootstrap || exit 1
+
+
 # Pull in the BOOK_CONFIGS
 source ./books.txt || exit 1
 
 
 # Check command line args
 
-if [ -z "${arg1}" ]
-then
-  >&2 echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument or --all for all books. For example: physics'
-  >&2 echo ''
-  >&2 echo "Valid books are (from ./books.txt):"
-  for bookConfig in "${BOOK_CONFIGS[@]}"
-  do
+if [[ ! "${arg1}" ]]; then
+  _say "Valid books are (from ./books.txt):"
+  for bookConfig in "${BOOK_CONFIGS[@]}"; do
     read -r bookName recipeName uuid _ <<< "${bookConfig}"
-    >&2 echo "${bookName}"
+    _say "${bookName}"
   done
-  exit 1
+  die 'Argument Missing. You must specify the name of the book as the 1st argument or --all for all books. For example: physics'
 fi
 
-if [ ! "${arg1}" == "--all" ]
-then
+if [[ ! "${arg1}" == "--all" ]]; then
   # Filter BOOK_CONFIGS to only contain the book you want to fetch
-  for bookConfig in "${BOOK_CONFIGS[@]}"
-  do
+  for bookConfig in "${BOOK_CONFIGS[@]}"; do
     read -r bookConfigName recipeName uuid hostName _ <<< "${bookConfig}"
 
-    if [[ "${arg1}" = "${bookConfigName}" ]]
-    then
+    if [[ "${arg1}" = "${bookConfigName}" ]]; then
       BOOK_CONFIGS=("${bookConfigName} ${recipeName} ${uuid} ${hostName} ${_}")
       hostName=${HOST:-${hostName}}
 
@@ -41,30 +39,23 @@ then
     fi
   done
 
-  if [[ ! 1 -eq "${foundConfig}" ]]
-  then
-    >&2 echo "ERROR: Could not find Book info for book named ${arg1}"
-    >&2 echo "Valid books are (from ./books.txt):"
+  if [[ ! 1 -eq "${foundConfig}" ]]; then
+    _say "Valid books are (from ./books.txt):"
     for bookConfig in "${BOOK_CONFIGS[@]}"
     do
       read -r bookName recipeName uuid _ <<< "${bookConfig}"
-      >&2 echo "${bookName}"
+      _say "${bookName}"
     done
-    exit 1
+    die "Could not find Book info for book named ${arg1}"
   fi
 fi
 
-for bookConfig in "${BOOK_CONFIGS[@]}"
-do
+for bookConfig in "${BOOK_CONFIGS[@]}"; do
   read -r bookName recipeName uuid hostName _ <<< "${bookConfig}"
   # Allow user to override the hostname
   hostName=${HOST:-${hostName}}
 
   rawFile="./data/${bookName}-raw.xhtml"
-
-  >&2 echo "==> Fetching ${bookName} from ${hostName}"
-  >&2 echo "generating an EPUB from the database and converting to a single HTML file"
-  >&2 echo "(may take a up to 20 minutes if you are getting a book with exercises that need to be converted)..."
 
   tempEpubFile="~/temp.internal.epub"
   tempHtmlFile="~/temp.xhtml"
@@ -76,11 +67,12 @@ do
 
   commands="${rmTempEpubCmd}; ${rmTempHtmlCmd}; ${generateEpubCmd} && ${generateHtmlCmd}"
 
-  ssh ${USER}@${hostName} ${commands}
+  do_progress_quiet "Fetching ${bookName} from ${hostName} (~20 minutes if it has exercises)" \
+    ssh ${USER}@${hostName} ${commands}
 
-  >&2 echo "==> Copying HTML file from server to local machine"
-  scp ${USER}@${hostName}:${tempHtmlFile} ${rawFile}
+  do_progress_quiet "Copying HTML file from server to local machine" \
+    scp ${USER}@${hostName}:${tempHtmlFile} ${rawFile}
 
-  >&2 echo "Fetch is Done. File is available at ${rawFile}"
+  _say "${c_green}Fetch is Done.${c_none} File is available at ${rawFile}"
 
 done
diff --git a/script/generate-guide b/script/generate-guide
--- a/script/generate-guide
+++ b/script/generate-guide
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+cd "$(dirname "$0")/.."
+
+source ./script/bootstrap || exit 1
+
 recipeName=$1
 bakedOrPreparedSuffix=$2 # Overridden when running ./diff-guide-prepare
 
@@ -18,156 +22,121 @@ sassBin="$(npm bin)/node-sass"
 
 # Check command line args
 
-if [ -z "${recipeName}" ]
-then
-  >&2 echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'
-  exit 1
-fi
+[[ "${recipeName}" ]] || die 'Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'
 
-if [ -z "${bakedOrPreparedSuffix}" ]
-then
+if [[ -z "${bakedOrPreparedSuffix}" ]]; then
   bakedOrPreparedSuffix="baked"
 else
-  >&2 echo "INFO: Generating -${bakedOrPreparedSuffix}.xhtml files instead of -baked.xhtml files"
+  _say "INFO: Generating -${bakedOrPreparedSuffix}.xhtml files instead of -baked.xhtml files"
 fi
 
 
->&2 echo "==> Compiling the guide.scss file for ${recipeName}"
-if [ ! -e ${styleguideDir} ]
-then
-  mkdir -p ${styleguideDir} || exit 1
-fi
+[[ -e ${styleguideDir} ]] || mkdir -p ${styleguideDir} || exit 111
+
+do_progress_quiet "Compiling the guide.scss file for ${recipeName}" \
+  ${sassBin} --source-map true ${sassFile} ${cssFile}
 
 
-${sassBin} --source-map true ${sassFile} ${cssFile} || exit 1
-
-
->&2 echo "==> Generating the baked example HTML files"
+progress "Generating the baked example HTML files"
 
 # Create a temporary directory which contains the recipes/mixins/ and recipes/${recipeName} directories.
 # This is because we want the styleguide to contain docs of all the common/ elements
 # and the book-specific elements, and kss only allows you to point to 1 directory
 # to look at all the SASS files.
-if [[ ! -d "${tempDir}" ]]
-then
-  mkdir "${tempDir}" || exit 1
-# Commented so we keep the directory because the lcov files are useful
-# else
-#   rm -rf "${tempDir}" || exit 1
-fi
+[[ -d "${tempDir}" ]] || mkdir "${tempDir}" || exit 111
 
 # Keep the tempRecipeDir around because it could have been created by diff-guide-prepare
-if [[ ! -d "${tempRecipeDir}" ]]
-then
-  mkdir "${tempRecipeDir}" || exit 1
-# else
-#   # rm -rf "${tempRecipeDir}" || exit 1
-fi
+[[ -d "${tempRecipeDir}" ]] || mkdir "${tempRecipeDir}" || exit 111
 
 
 # Copy over all the dirs containing the styleguide comments that need to be included
 
 # Pull in the BOOK_CONFIGS
-source ./books.txt || exit 1
+source ./books.txt || exit 111
 
 # Filter BOOK_CONFIGS to only contain the book you want to fetch
-for bookConfig in "${BOOK_CONFIGS[@]}"
-do
+for bookConfig in "${BOOK_CONFIGS[@]}"; do
   read -r bookConfigName recipeConfigName uuid hostName basedOns <<< "${bookConfig}"
 
-  if [[ "${recipeName}" = "${recipeConfigName}" ]]
-  then
+  if [[ "${recipeName}" = "${recipeConfigName}" ]]; then
     # Actually copy the directories over (like common/,books/physics/)
     IFS=',' read -ra basedOnDirs <<< "$basedOns"
     for basedOnDirName in "${basedOnDirs[@]}"; do
-      echo "==> Including ${sassDir}/${basedOnDirName}"
-      cp -R "${sassDir}/${basedOnDirName}" "${tempRecipeDir}/$(basename ${basedOnDirName})" || exit 1
+      do_progress_quiet "Including ${sassDir}/${basedOnDirName}" \
+        cp -R "${sassDir}/${basedOnDirName}" "${tempRecipeDir}/$(basename ${basedOnDirName})"
     done
     foundConfig=1
     break
   fi
 done
 
-if [[ ! 1 -eq "${foundConfig}" ]]
-then
-  >&2 echo "ERROR: Could not find Book info for book named ${recipeName}"
-  >&2 echo "check ./books.txt"
-  exit 1
-fi
+[[ 1 -eq "${foundConfig}" ]] || die "Could not find Book info for book named ${recipeName}. check ./books.txt"
 
-cp -R "${bookDocumentationDir}" "${tempRecipeDir}" || exit 1
+cp -R "${bookDocumentationDir}" "${tempRecipeDir}" || exit 111
 
 
 # Find all the styleguide html files and convert them
-for snippetFileName in $(find "${tempRecipeDir}" -name "*.snippet.xml")
-do
+for snippetFileName in $(find "${tempRecipeDir}" -name "*.snippet.xml"); do
 
   snippetBase="$(dirname "${snippetFileName}")/$(basename "${snippetFileName}" .snippet.xml)"
   rawFileName="${snippetBase}.raw.xhtml"
   # This is the filename in the CSS comment
   destFileName="${snippetBase}.xhtml-${bakedOrPreparedSuffix}.html"
 
-  >&2 echo "Generating temporary ${snippetFileName}-${bakedOrPreparedSuffix}.html"
-
   # Convert the snippet (which is HTML + CNXML) into just HTML
-  xsltproc ./script/_cnxml-to-xhtml.xsl "${snippetFileName}" > "${rawFileName}" || exit 1
+  xsltproc ./script/_cnxml-to-xhtml.xsl "${snippetFileName}" > "${rawFileName}" || exit 111
 
   # commented because xmllint does not like html5 element names like <figure>
   # ./script/bake-file ${recipeName} ${snippetFileName} /dev/stdout | xmllint --html --format - > ${snippetFileName}-baked.xhtml
-  ./script/bake-file ${recipeName} ${rawFileName} ${rawFileName}-temp1-${bakedOrPreparedSuffix}.xhtml --use-repeatable-ids  || exit 1
+  # use `source` so we do not have to re-initialize python/node/ruby
+  do_progress_quiet "Baking ${rawFileName}" \
+    source ./script/bake-file ${recipeName} ${rawFileName} ${rawFileName}-temp1-${bakedOrPreparedSuffix}.xhtml --use-repeatable-ids  || exit 111
 
   # Construct an HTML file that contains both the raw and baked HTML
   # so it can be separated in the browser
   # (and so Phil does not have to completely rewrite kss becuase it assumes only 1 file for markup)
-  echo '<section class="-kss-autogen-guide-markup" data-kss-format="cnxml">' > "${destFileName}" || exit 1
-  cat ${snippetFileName} >> "${destFileName}" || exit 1
-  echo '</section>' >> "${destFileName}" || exit 1
-  echo '<section class="-kss-autogen-guide-markup" data-kss-format="html-raw">' >> "${destFileName}" || exit 1
-  cat ${rawFileName} >> "${destFileName}" || exit 1
-  echo '</section>' >> "${destFileName}" || exit 1
-  echo '<section class="-kss-autogen-guide-markup" data-kss-format="html-baked">' >> "${destFileName}" || exit 1
-  cat ${rawFileName}-temp1-${bakedOrPreparedSuffix}.xhtml >> "${destFileName}" || exit 1
-  echo '</section>' >> "${destFileName}" || exit 1
+  echo '<section class="-kss-autogen-guide-markup" data-kss-format="cnxml">' > "${destFileName}" || exit 111
+  cat ${snippetFileName} >> "${destFileName}" || exit 111
+  echo '</section>' >> "${destFileName}" || exit 111
+  echo '<section class="-kss-autogen-guide-markup" data-kss-format="html-raw">' >> "${destFileName}" || exit 111
+  cat ${rawFileName} >> "${destFileName}" || exit 111
+  echo '</section>' >> "${destFileName}" || exit 111
+  echo '<section class="-kss-autogen-guide-markup" data-kss-format="html-baked">' >> "${destFileName}" || exit 111
+  cat ${rawFileName}-temp1-${bakedOrPreparedSuffix}.xhtml >> "${destFileName}" || exit 111
+  echo '</section>' >> "${destFileName}" || exit 111
 
-  rm ${rawFileName}-temp1-${bakedOrPreparedSuffix}.xhtml || exit 1
+  rm ${rawFileName}-temp1-${bakedOrPreparedSuffix}.xhtml || exit 111
 done
 
 
-if [[ "${bakedOrPreparedSuffix}" == "baked" ]]
-then
+if [[ "${bakedOrPreparedSuffix}" == "baked" ]]; then
 
-  >&2 echo "==> Generating the style guide"
   # The CSS path is relative to the styleguide directory, hence `./guide.css`
   # Exclude parsing the output/*.css files by setting the --mask
-  $(npm bin)/kss-node --template ./js/openstax-kss-builder --verbose --homepage ${guideHomepageFile} --destination ${styleguideDir} --css ./guide.css --source ${tempRecipeDir} --mask '*.less|*.sass|*.scss|*.styl|*.stylus' > "${kssOutputFile}"  || exit 1
-
-  # Delete the temp files created above
-  # >&2 echo "==> Deleting the baked example HTML files"
-  # for snippetFileName in $(find ./recipes/books/ -name "*-${bakedOrPreparedSuffix}.xhtml")
-  # do
-  #   # echo "Removing temporary ${snippetFileName}"
-  #   rm ${snippetFileName} || exit 1
-  # done
+  do_progress_quiet "Generating the style guide" \
+    $(npm bin)/kss-node --verbose \
+    --template ./js/openstax-kss-builder \
+    --homepage ${guideHomepageFile} \
+    --destination ${styleguideDir} \
+    --css ./guide.css \
+    --source ${tempRecipeDir} \
+    --mask '*.less|*.sass|*.scss|*.styl|*.stylus' > "${kssOutputFile}"
 
   # HACK: KSS-node does not error if an HTML file is missing. Instead, it prints out a warning.
   # So, check the output of kss to see if any errors were reported.
   missingFiles=$(cat "${kssOutputFile}" | grep 'NOT FOUND!' )
-  if [ -n "${missingFiles}" ]
-  then
-    >&2 echo "ERROR: Some HTML files were missing:"
-    >&2 echo "${missingFiles}"
-    >&2 echo "Check ${kssOutputFile} for more details"
-    exit 1
+  if [[ -n "${missingFiles}" ]]; then
+    die "Some HTML files were missing: ${missingFiles}. Check ${kssOutputFile} for more details"
   fi
 
   # Generate an HTML report (if genhtml is installed)
-  if [[ -n "$(which genhtml)" ]]
-  then
-    genhtml --quiet --output ./coverage/ $(find "${tempRecipeDir}" -name "*.lcov")
+  if [[ -n "$(which genhtml)" ]]; then
+    do_progress_quiet "Generating HTML coverage report" \
+      genhtml --quiet --output ./coverage/ $(find "${tempRecipeDir}" -name "*.lcov")
   fi
 
-  >&2 echo "Guide is available at ${styleguideDir} . You can open it in a browser"
+  _say "Guide is available at ${styleguideDir}/index.html . You can open it in a browser"
 
 else
-  >&2 echo "INFO: Skipping actual styleguide generation because the additional arg '${bakedOrPreparedSuffix}' was provided (probably for diff-guide-prepare)"
+  _say "INFO: Skipping actual styleguide generation because the additional arg '${bakedOrPreparedSuffix}' was provided (probably for diff-guide-prepare)"
 fi
