clarify instructions if .python-version file is missing

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -98,11 +98,11 @@ if [[ ! ${BOOTSTRAP_ALREADY_RAN} ]]; then
     # Only install & activate the virtualenv if not already in one
     if [[ -z "${VIRTUAL_ENV}" ]]; then
 
+      # Check that a .python-version file is set
+      [[ -f "./.python-version" ]] || die "Repository is missing a .python-version file. Please add one. The contents should contain the python version (ie 2.7)"
+
       virtualenv_dir="./venv/"
       python_version="$(< .python-version)"
-
-      # Check that a .python-version file is set
-      [[ -f "./.python-version" ]] || die "Repository is missing a .python-version file. Please add one"
 
       # macOS needs a little extra love
       if [[ -f "Brewfile" ]] && [[ "$(uname -s)" = "Darwin" ]]; then
