switch back to just using virtualenv
and hope that the ~/.pyenv/shims/virtualenv runs

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -103,7 +103,6 @@ if [[ ! ${BOOTSTRAP_ALREADY_RAN} ]]; then
 
       virtualenv_dir="./venv/"
       python_version="$(< .python-version)"
-      virtualenv_command="virtualenv"
 
       # macOS needs a little extra love
       if [[ "$(uname -s)" = "Darwin" ]]; then
@@ -116,8 +115,8 @@ if [[ ! ${BOOTSTRAP_ALREADY_RAN} ]]; then
         eval "$(pyenv init -)"
         eval "$(pyenv virtualenv-init -)"
 
-        # Use the pyenv virtualenv instead of one that was installed on the system
-        virtualenv_command="pyenv virtualenv"
+        # Check that `virtualenv` points to the pyenv version
+        [[ $(pyenv which virtualenv) ]] || die "wrong version of virtualenv. Maybe Brewfile is missing an entry for pyenv-virtualenv or you might need to: 'brew uninstall pyenv; brew uninstall pyenv-virtualenv; rm -rf ~/.pyenv/' and then re-run the setup script"
 
       fi
 
@@ -138,10 +137,9 @@ if [[ ! ${BOOTSTRAP_ALREADY_RAN} ]]; then
           pip install virtualenv
       fi
       # Create a virtualenv
-      # shellcheck disable=SC2086
       if [[ ! -d "${virtualenv_dir}" ]]; then
         do_progress_quiet "Setting up a Python virtualenv" \
-          ${virtualenv_command} "${virtualenv_dir}"
+          virtualenv "${virtualenv_dir}"
       fi
 
       do_progress_quiet "Activating Python virtualenv" \
