check for xmllint

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -63,3 +63,9 @@ if [ -f "Gemfile" ]; then
     bundle install --path vendor/gems --quiet --without production
   }
 fi
+
+
+which xmllint >/dev/null 2>&1 || {
+  >&2 echo "ERROR: xmllint is not installed. Please install it first"
+  exit 1
+}
