:art: update scripts
This way they are consistent with the ones in oer.exports

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -3,73 +3,128 @@
 # Resolve all dependencies that the application requires to run.
 # From https://github.com/github/scripts-to-rule-them-all/blob/master/script/bootstrap
 
-set -e
-
 cd "$(dirname "$0")/.."
 
-if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
-  >&2 echo "==> Updating Homebrew…"
-  brew update || exit 1
+
+# https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
+if [[ $(tput colors) -ge 8 ]]; then
+  c_none=$(tput sgr0)
+  c_red=$(tput setaf 1)
+  c_green=$(tput setaf 2)
+  c_blue=$(tput setaf 4)
+  c_purple=$(tput setaf 5)
+  c_dark=$(tput setaf 8)
+  c_yellow=$(tput setaf 11)
+  c_cyan=$(tput setaf 14)
+fi
+
+_say() { echo -e "$1"; }
+progress() { _say "${c_yellow}==>${c_none} $1"; }
+# https://stackoverflow.com/a/25515370
+yell() { >&2 _say "$0: ${c_red}$*${c_none}"; }
+die() {
+  yell "$1"
+  if [[ $2 ]]; then
+    err_code=$2
+  else
+    err_code=112
+  fi
+  exit ${err_code}
+}
+try() { "$@" || die "${c_red}ERROR: could not run [$*]${c_none}" 112; }
+
+do_progress() { progress "$1"; try "${@:2}"; }
+
+# Alternative that outputs only when an error occurs
+_quiet_progress() { echo -e -n "${c_yellow}==>${c_none} $1 ${c_dark}...${c_none} "; }
+_quiet_try() {
+  _myout=$(mktemp -t 'stdout')
+  _myerr=$(mktemp -t 'stderr')
+  "$@" > ${_myout} 2> ${_myerr} || {
+    echo "" # start on a new line
+    cat ${_myout}
+    >&2 cat ${_myerr}
+    rm ${_myout} ${_myerr}
+    die "${c_red}ERROR: could not run [$*]${c_none}"
+  }
+  rm ${_myout} ${_myerr}
+}
+_quiet_ok() { _say "${c_green}OK${c_none}"; }
+do_progress_quiet() {
+  # Keep it loud when running in Travis or Jenkins
+  if [[ "${CI}" == "true" || "${JENKINS_URL}" != "" || "${DEBUG}" || "${VERBOSE}" ]]; then
+    do_progress "$@"
+  else
+    _quiet_progress "$1"
+    _quiet_try "${@:2}" # Skip the 1st arg but use the rest
+    _quiet_ok
+  fi
+}
+
+
+# Install homebrew packages if running on macOS
+if [[ -f "Brewfile" ]] && [[ "$(uname -s)" = "Darwin" ]]; then
+  [[ $(which brew) ]] || die "Homebrew is not installed. See https://brew.sh"
+  [[ $(xcode-select --print-path) == "/Library/Developer/CommandLineTools" ]] || _say "${c_red}WARNING:${c_none} You may need to uninstall XCode and just install the command line tools"
 
   brew bundle check >/dev/null 2>&1  || {
-    >&2 echo "==> Installing Homebrew dependencies…"
-    brew bundle || exit 1
+    do_progress "Installing Homebrew dependencies…" \
+      brew bundle
   }
 fi
 
+# Python: Install & Activate python virtualenv
+if [[ ! "${CI}" = "true" && -f "./setup.py" ]]; then
+  # Only install & activate the virtualenv if not already in one
+  if [[ -z "${VIRTUAL_ENV}" ]]; then
 
-if [[ ! "${CI}" = "true" && ! $(which virtualenv) ]]; then
-  >&2 echo "ERROR: virtualenv (Python Virtualenv) is not installed. Please install it"
-  exit 1
-fi
+    if [[ ! $(which virtualenv) ]]; then
+      # macOS needs a little extra love
+      if [[ -f "Brewfile" ]] && [[ "$(uname -s)" = "Darwin" ]]; then
+        do_progress_quiet "Unlinking homebrew python (just-in-case)" \
+          brew unlink python
+        do_progress_quiet "Relinking homebrew python" \
+          brew link python
+      fi
 
-if [[ ! "${CI}" = "true" && ! $(which node) ]]; then
-  >&2 echo "ERROR: node (NodeJS) is not installed. Please install it by going to https://github.com/creationix/nvm"
-  exit 1
-fi
-
-
-
->&2 echo "==> Installing Node package dependencies"
->&2 echo "Using node: $(node --version)"
->&2 echo "Using npm: $(npm --version)"
-
-# Install https://yarnpkg.com (package manager)
-if [[ ! $(which yarn) ]]; then
-  # Prompt when on debian
-  if [[ $(which apt-key) ]]; then
-    read -p "Would you like to install yarn (y/N)? This will use sudo to install a 3rd party apt repository, and install the yarn package." choice
-    echo # Move to a new line
-    if [[ "${choice}" =~ ^[Yy]$ ]]; then
-      >&2 echo "==> Installing yarn. You may be prompted for a password"
-      curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - || exit 1
-      echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list || exit 1
-      sudo apt-get update && sudo apt-get install yarn || exit 1
-    else
-      echo "Yarn is not installed. Exiting"
-      echo "To install yarn manually, follow the instructions at https://yarnpkg.com/en/docs/install#linux-tab"
-      exit 1
+      do_progress_quiet "Installing Python virtualenv" \
+        pip install virtualenv
     fi
+    if [[ ! -d "./venv/" ]]; then
+      do_progress_quiet "Setting up a python virtualenv" \
+        virtualenv ./venv/
+    fi
+    do_progress_quiet "Activating virtualenv" \
+      source ./venv/bin/activate
   else
-    echo "Not sure how to install yarn automatically. If you are using macOS do you have https://brew.sh installed?"
-    echo "To install yarn manually, follow the instructions at https://yarnpkg.com"
-    exit 1
+    >&2 echo "Skipping virtualenv because already in one"
+  fi
+fi
+
+# Javascript environment
+if [[ -f "./package.json" ]]; then
+  [[ $(which yarn) ]] || die "ERROR: Install yarn by going to https://yarnpkg.com"
+fi
+if [[ -f "./.nvmrc" ]]; then
+  # Set up the correct version of node (Travis automatically does this)
+  if [[ ! "${CI}" = "true" ]]; then
+    if [[ ! -f ~/.nvm/nvm.sh ]]; then
+      die "ERROR: Install nvm by going to https://github.com/creationix/nvm"
+    fi
+    source ~/.nvm/nvm.sh --no-use
+    do_progress_quiet "Setting correct node version (see ./.nvmrc)" \
+      nvm install $(< ./.nvmrc)
   fi
 fi
 
 # Note: Skip rbenv for Travis because it already has ruby
-if [ ! "${CI}" = "true" ] && [ -f ".ruby-version" ]; then
+if [[ ! "${CI}" = "true" ]] && [[ -f ".ruby-version" ]]; then
   if [[ -n $(which rbenv) ]]; then
-
+    progress "Setting correct ruby version (see ./.ruby-version)"
     rbenv_version="$(rbenv version-name 2>/dev/null)"
-    if [ -z "${rbenv_version}" ]; then
-      >&2 echo "==> Installing Ruby…"
-      rbenv install --skip-existing || {
-        echo "WARNING: 'rbenv install' errored. I am assuming you know what you are doing (and have sass installed locally) so continuing"
-        exit 0
-      }
-    else
-      echo "Using rbenv ruby: ${rbenv_version}"
+    if [[ -z "${rbenv_version}" ]]; then
+      do_progress_quiet "Installing Ruby" \
+        rbenv install --skip-existing
     fi
   else
     >&2 echo "WARNING: Skipping rbenv. Using local ruby"
@@ -79,7 +134,7 @@ if [ ! "${CI}" = "true" ] && [ -f ".ruby-version" ]; then
   [[ -n $(which rbenv) ]] && eval "$(rbenv init -)"
 
   gem list -i bundler >/dev/null 2>&1  || {
-    >&2 echo "==> Installing Ruby Bundler gem…"
+    progress "Installing Ruby Bundler gem…"
     gem install bundler || {
       >&2 echo ''
       >&2 echo ''
@@ -92,17 +147,3 @@ if [ ! "${CI}" = "true" ] && [ -f ".ruby-version" ]; then
 
   }
 fi
-
-if [ -f "Gemfile" ]; then
-  >&2 echo "==> Installing gem dependencies…"
-  which bundle
-  bundle check --path vendor/gems >/dev/null 2>&1  || {
-    bundle install --path vendor/gems --quiet --without production
-  }
-fi
-
-
-which xmllint >/dev/null 2>&1 || {
-  >&2 echo "ERROR: xmllint is not installed. Please install it first"
-  exit 1
-}
diff --git a/script/setup b/script/setup
--- a/script/setup
+++ b/script/setup
@@ -1,60 +1,42 @@
 #!/bin/bash
 set -e
 
-./script/bootstrap || exit 1
+cd "$(dirname "$0")/.."
 
->&2 echo "==> Installing JavaScript Packages"
-if [[ $(which yarn) ]]; then
-  yarn install || exit 1
-else
-  >&2 echo "WARNING: Installing JS packages using npm instead of yarn."
-  npm install || exit 1
-fi
+source ./script/bootstrap || exit 1
 
+# JavaScript stuff
+do_progress_quiet "Installing JavaScript Packages" \
+  yarn --prefer-offline
 
-# Only activate the virtualenv if not already in one
-if [[ -z "${VIRTUAL_ENV}" ]]
-then
+# Python stuff
+if [[ -f "./requirements.txt" || -f "./setup.py" ]]; then
 
-  # This is mostly for travis
-  if [[ -z "$(which virtualenv)" ]]
-  then
-    >&2 echo "==> Installing Python virtualenv (pip install virtualenv)"
-    pip install virtualenv
+  if [[ -n "${VIRTUAL_ENV}" ]]; then
+    if [[ -f "./requirements.txt" ]]; then
+      do_progress_quiet "Installing python packages" \
+        pip install -r "./requirements.txt"
+    else
+      if [[ -f "./setup.py" ]]; then
+        do_progress_quiet "Installing python packages from setup.py" \
+          python setup.py install
+      fi
+    fi
+  else
+    echo "ERROR. Not in a virtualenv"
+    exit 1
   fi
-
-  >&2 echo "==> Setting up a python virtualenv"
-  virtualenv ./venv/
-  source ./venv/bin/activate
-else
-  >&2 echo "==> Skipping virtualenv because already in one"
 fi
 
-pip install -U pip
-
-if [[ -n "${VIRTUAL_ENV}" ]]
-then
-
-  >&2 echo "==> Installing python packages"
-  pip install -r ./requirements.txt
-
-else
-  echo "ERROR. Not in a virtualenv"
-  exit 1
+# Ruby stuff
+if [[ -f "./Gemfile" ]]; then
+  bundle check --path ./vendor/gems >/dev/null 2>&1  || {
+    do_progress_quiet "Installing ruby gems" \
+      bundle install --path ./vendor/gems --quiet --without production
+  }
 fi
 
 
-# Clone the rhaptos.cnxmlutils repo in here
-if [[ ! -d ./vendor/rhaptos.cnxmlutils/.git/ ]]; then
-  >&2 echo "==> Installing ./vendor/rhaptos.cnxmlutils/"
-  git clone https://github.com/Connexions/rhaptos.cnxmlutils.git ./vendor/rhaptos.cnxmlutils/
-else
-  >&2 echo "==> Using existing ./vendor/rhaptos.cnxmlutils/"
-fi
+# Setup stuff that is custom to this repo
 
->&2 echo "==> Checking out branch in ./vendor/rhaptos.cnxmlutils/ (see https://github.com/Connexions/rhaptos.cnxmlutils/pull/157)"
-
-cd "./vendor/rhaptos.cnxmlutils/"
-git checkout rng-fixes
-git pull
-cd ..
+_say "${c_green}Successfully set up${c_none}"
