Use pyenv to specify python version
See https://brew.sh/2018/01/19/homebrew-1.5.0/

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -8,8 +8,18 @@ if [[ $0 != "-bash" ]]; then
   cd "$(dirname "$0")/.." || exit 111
 fi
 
+# Set the LOG_LEVEL to "info" if it is not set
+if [[ ! "${LOG_LEVEL}" ]]; then
+  if [[ "${DEBUG}" ]]; then
+    echo "(deprecated) use LOG_LEVEL='debug' rather than DEBUG=true to enable debugging"
+    LOG_LEVEL="debug"
+  else
+    LOG_LEVEL="info"
+  fi
+fi
+
 # Turn on tracing if desired
-[[ ${TRACE} == "true" ]] && set -x
+[[ ${LOG_LEVEL} == "trace" ]] && set -x
 
 # https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
 if [[ $(tput colors) -ge 8 ]]; then
@@ -60,7 +70,7 @@ _quiet_ok() {
 }
 do_progress_quiet() {
   # Keep it loud when running in Travis or Jenkins
-  if [[ "${TRACE}" || "${DEBUG}" || "${VERBOSE}" || "${__NESTED_PROGRESS__}" == "true" ]]; then
+  if [[ "${LOG_LEVEL}" == "trace" || "${LOG_LEVEL}" == "debug" || "${__NESTED_PROGRESS__}" == "true" ]]; then
     do_progress "$@"
   else
     _quiet_progress "$1"
@@ -88,24 +98,46 @@ if [[ ! ${BOOTSTRAP_ALREADY_RAN} ]]; then
     # Only install & activate the virtualenv if not already in one
     if [[ -z "${VIRTUAL_ENV}" ]]; then
 
-      if [[ ! $(which virtualenv) ]]; then
-        # macOS needs a little extra love
-        if [[ -f "Brewfile" ]] && [[ "$(uname -s)" = "Darwin" ]]; then
-          do_progress_quiet "Unlinking homebrew python (just-in-case)" \
-            brew unlink python
-          do_progress_quiet "Relinking homebrew python" \
-            brew link python
-        fi
+      virtualenv_dir="./venv/"
+      python_version="$(< .python-version)"
 
+      # Check that a .python-version file is set
+      [[ -f "./.python-version" ]] || die "Repository is missing a .python-version file. Please add one"
+
+      # macOS needs a little extra love
+      if [[ -f "Brewfile" ]] && [[ "$(uname -s)" = "Darwin" ]]; then
+        # Install the correct python version if it is not installed yet
+        if [[ ! $(pyenv which python) ]]; then
+          do_progress_quiet "Installing Python ${python_version} (using pyenv)" \
+            pyenv install "${python_version}"
+        fi
+        eval "$(pyenv init -)"
+      fi
+
+      # Install pip if it is not available
+      if [[ ! $(which pip) ]]; then
+        pwd=$(pwd)
+        do_progress_quiet "Downloading pip" \
+          curl --output "${pwd}/get-pip.py" https://bootstrap.pypa.io/get-pip.py
+        do_progress_quiet "Installing pip" \
+          python "${pwd}/get-pip.py"
+        do_progress_quiet "Cleaning up after pip installation" \
+          rm "${pwd}/get-pip.py"
+      fi
+
+      # Install virtualenv
+      if [[ ! $(which virtualenv) ]]; then
         do_progress_quiet "Installing Python virtualenv" \
           pip install virtualenv
       fi
-      if [[ ! -d "./venv/" ]]; then
-        do_progress_quiet "Setting up a python virtualenv" \
-          virtualenv ./venv/
+      # Create a virtualenv
+      if [[ ! -d "${virtualenv_dir}" ]]; then
+        do_progress_quiet "Setting up a Python virtualenv" \
+          virtualenv "${virtualenv_dir}"
       fi
-      do_progress_quiet "Activating virtualenv" \
-        source ./venv/bin/activate
+
+      do_progress_quiet "Activating Python virtualenv" \
+        source "${virtualenv_dir}/bin/activate"
     else
       _say "${c_yellow}Skipping virtualenv${c_none} because already in one"
     fi
