do not reinitialize node/ruby

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -5,70 +5,72 @@
 
 cd "$(dirname "$0")/.."
 
-if [[ ! ${BOOTSTRAP_ALREADY_RAN} ]]; then
 
-  # https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
-  if [[ $(tput colors) -ge 8 ]]; then
-    c_none=$(tput sgr0)
-    c_red=$(tput setaf 1)
-    c_green=$(tput setaf 2)
-    c_blue=$(tput setaf 4)
-    c_purple=$(tput setaf 5)
-    c_dark=$(tput setaf 8)
-    c_yellow=$(tput setaf 11)
-    c_cyan=$(tput setaf 14)
+
+# https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
+if [[ $(tput colors) -ge 8 ]]; then
+  c_none=$(tput sgr0)
+  c_red=$(tput setaf 1)
+  c_green=$(tput setaf 2)
+  c_blue=$(tput setaf 4)
+  c_purple=$(tput setaf 5)
+  c_dark=$(tput setaf 8)
+  c_yellow=$(tput setaf 11)
+  c_cyan=$(tput setaf 14)
+fi
+
+_say() { echo -e "$1"; }
+progress() { _say "${c_yellow}==>${c_none} $1"; }
+# https://stackoverflow.com/a/25515370
+yell() { >&2 _say "$0: ${c_red}$*${c_none}"; }
+die() {
+  yell "$1"
+  if [[ $2 ]]; then
+    err_code=$2
+  else
+    err_code=112
   fi
+  exit ${err_code}
+}
+try() { __NESTED_PROGRESS__="true" "$@" || die "${c_red}ERROR: could not run [$*]${c_none}" 112; }
 
-  _say() { echo -e "$1"; }
-  progress() { _say "${c_yellow}==>${c_none} $1"; }
-  # https://stackoverflow.com/a/25515370
-  yell() { >&2 _say "$0: ${c_red}$*${c_none}"; }
-  die() {
-    yell "$1"
-    if [[ $2 ]]; then
-      err_code=$2
-    else
-      err_code=112
-    fi
-    exit ${err_code}
-  }
-  try() { __NESTED_PROGRESS__="true" "$@" || die "${c_red}ERROR: could not run [$*]${c_none}" 112; }
+do_progress() { progress "$1"; try "${@:2}"; }
 
-  do_progress() { progress "$1"; try "${@:2}"; }
-
-  # Alternative that outputs only when an error occurs
-  _quiet_progress() { echo -e -n "${c_yellow}==>${c_none} $1 ${c_dark}...${c_none} "; }
-  _quiet_try() {
-    SECONDS=0
-    _myout=$(mktemp -t 'stdout')
-    _myerr=$(mktemp -t 'stderr')
-    __NESTED_PROGRESS__="true" "$@" > ${_myout} 2> ${_myerr} || {
-      echo "" # start on a new line
-      cat ${_myout}
-      >&2 cat ${_myerr}
-      rm ${_myout} ${_myerr}
-      die "${c_red}ERROR: could not run [$*]${c_none}"
-    }
+# Alternative that outputs only when an error occurs
+_quiet_progress() { echo -e -n "${c_yellow}==>${c_none} $1 ${c_dark}...${c_none} "; }
+_quiet_try() {
+  SECONDS=0
+  _myout=$(mktemp -t 'stdout')
+  _myerr=$(mktemp -t 'stderr')
+  __NESTED_PROGRESS__="true" "$@" > ${_myout} 2> ${_myerr} || {
+    echo "" # start on a new line
+    cat ${_myout}
+    >&2 cat ${_myerr}
     rm ${_myout} ${_myerr}
+    die "${c_red}ERROR: could not run [$*]${c_none}"
   }
-  _quiet_ok() {
-    time_spent=""
-    if [[ ${SECONDS} -gt 5 ]]; then
-      time_spent=" ${c_dark}(${SECONDS} sec)${c_none}"
-    fi
-    _say "${c_green}OK${c_none}${time_spent}";
-  }
-  do_progress_quiet() {
-    # Keep it loud when running in Travis or Jenkins
-    if [[ "${CI}" == "true" || "${JENKINS_URL}" != "" || "${DEBUG}" || "${VERBOSE}" || "${__NESTED_PROGRESS__}" == "true" ]]; then
-      do_progress "$@"
-    else
-      _quiet_progress "$1"
-      _quiet_try "${@:2}" # Skip the 1st arg but use the rest
-      _quiet_ok
-    fi
-  }
+  rm ${_myout} ${_myerr}
+}
+_quiet_ok() {
+  time_spent=""
+  if [[ ${SECONDS} -gt 5 ]]; then
+    time_spent=" ${c_dark}(${SECONDS} sec)${c_none}"
+  fi
+  _say "${c_green}OK${c_none}${time_spent}";
+}
+do_progress_quiet() {
+  # Keep it loud when running in Travis or Jenkins
+  if [[ "${CI}" == "true" || "${JENKINS_URL}" != "" || "${DEBUG}" || "${VERBOSE}" || "${__NESTED_PROGRESS__}" == "true" ]]; then
+    do_progress "$@"
+  else
+    _quiet_progress "$1"
+    _quiet_try "${@:2}" # Skip the 1st arg but use the rest
+    _quiet_ok
+  fi
+}
 
+# This provides a > 10% speedup because we do not have to reinitialize node and ruby
+if [[ ! ${BOOTSTRAP_ALREADY_RAN} ]]; then
 
   # Install homebrew packages if running on macOS
   if [[ -f "Brewfile" ]] && [[ "$(uname -s)" = "Darwin" ]]; then
@@ -156,8 +158,6 @@ if [[ ! ${BOOTSTRAP_ALREADY_RAN} ]]; then
     }
   fi
 
-
-  BOOTSTRAP_ALREADY_RAN="true"
-# else
-#   die "Bootstrap already ran"
+  # Trust that subshells will maintain the python/node/ruby version
+  declare -x BOOTSTRAP_ALREADY_RAN="true"
 fi
