replace all references to "ruleset" with "recipe"

diff --git a/script/diff-guide b/script/diff-guide
--- a/script/diff-guide
+++ b/script/diff-guide
@@ -15,12 +15,12 @@ source ./books.txt || exit 1
 if [[ ! "${arg1}" == "--all" ]]
 then
   # Filter BOOK_CONFIGS to only contain the book you want to fetch
-  for rulesetName in "${RULESET_NAMES[@]}"
+  for recipeName in "${RECIPE_NAMES[@]}"
   do
 
-    if [[ "${arg1}" = "${rulesetName}" ]]
+    if [[ "${arg1}" = "${recipeName}" ]]
     then
-      RULESET_NAMES=("${rulesetName}")
+      RECIPE_NAMES=("${recipeName}")
       foundConfig=1
       break
     fi
@@ -28,23 +28,23 @@ then
 
   if [[ ! 1 -eq "${foundConfig}" ]]
   then
-    >&2 echo "ERROR: Could not find Book info for ruleset named ${arg1}"
+    >&2 echo "ERROR: Could not find Book info for recipe named ${arg1}"
     >&2 echo "Valid books are (from ./books.txt):"
-    for rulesetName in "${RULESET_NAMES[@]}"
+    for recipeName in "${RECIPE_NAMES[@]}"
     do
-      >&2 echo "${rulesetName}"
+      >&2 echo "${recipeName}"
     done
     exit 1
   fi
 fi
 
 diffFound=0
-for rulesetName in "${RULESET_NAMES[@]}"
+for recipeName in "${RECIPE_NAMES[@]}"
 do
 
-  >&2 echo "==> Checking for differences in '${rulesetName}'"
+  >&2 echo "==> Checking for differences in '${recipeName}'"
 
-  for bakedFile in $(find ./tmp/${rulesetName} -name "*-baked.xhtml")
+  for bakedFile in $(find ./tmp/${recipeName} -name "*-baked.xhtml")
   do
 
     preparedFile="${bakedFile/-baked/-prepared}"
@@ -61,8 +61,8 @@ do
       fi
 
     else
-      >&2 echo "FAILING ${rulesetName} because the prepared file '${preparedFile}' was not found."
-      >&2 echo "Did you run './script/diff-guide-prepare ${rulesetName}' earlier?"
+      >&2 echo "FAILING ${recipeName} because the prepared file '${preparedFile}' was not found."
+      >&2 echo "Did you run './script/diff-guide-prepare ${recipeName}' earlier?"
       exit 1
     fi
 
diff --git a/script/generate-guide b/script/generate-guide
--- a/script/generate-guide
+++ b/script/generate-guide
@@ -1,23 +1,23 @@
 #!/bin/bash
 
-rulesetName=$1
+recipeName=$1
 bakedOrPreparedSuffix=$2 # Overridden when running ./diff-guide-prepare
 
-sassDir='./rulesets/'
-styleguideDir="./styleguide/${rulesetName}"
-sassFile="${sassDir}/books/${rulesetName}/book.scss"
+sassDir='./recipes/'
+styleguideDir="./styleguide/${recipeName}"
+sassFile="${sassDir}/books/${recipeName}/book.scss"
 cssFile="${styleguideDir}/guide.css"
-bookCssFile="${sassDir}/output/${rulesetName}.css"
-guideHomepageFile="./guide-homepage.md" # Relative to ${sassDir}/rulesets/
+bookCssFile="${sassDir}/output/${recipeName}.css"
+guideHomepageFile="./guide-homepage.md" # Relative to ${sassDir}/recipes/
 
 tempDir="./tmp/"
-tempRulesetDir="${tempDir}/${rulesetName}/"
-bookDocumentationDir="./rulesets/books/${rulesetName}"
+tempRecipeDir="${tempDir}/${recipeName}/"
+bookDocumentationDir="./recipes/books/${recipeName}"
 kssOutputFile="${tempDir}/kss-output.txt"
 
 # Check command line args
 
-if [ -z "${rulesetName}" ]
+if [ -z "${recipeName}" ]
 then
   >&2 echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'
   exit 1
@@ -34,7 +34,7 @@ fi
 [[ -n $(which rbenv) ]] && eval "$(rbenv init -)"
 
 
->&2 echo "==> Compiling the guide.scss file for ${rulesetName}"
+>&2 echo "==> Compiling the guide.scss file for ${recipeName}"
 if [ ! -e ${styleguideDir} ]
 then
   mkdir -p ${styleguideDir} || exit 1
@@ -60,7 +60,7 @@ ${sassBin} ${sassFile} ${bookCssFile} || exit 1
 
 >&2 echo "==> Generating the baked example HTML files"
 
-# Create a temporary directory which contains the rulesets/mixins/ and rulesets/${rulesetName} directories.
+# Create a temporary directory which contains the recipes/mixins/ and recipes/${recipeName} directories.
 # This is because we want the styleguide to contain docs of all the common/ elements
 # and the book-specific elements, and kss only allows you to point to 1 directory
 # to look at all the SASS files.
@@ -72,12 +72,12 @@ then
 #   rm -rf "${tempDir}" || exit 1
 fi
 
-# Keep the tempRulesetDir around because it could have been created by diff-guide-prepare
-if [[ ! -d "${tempRulesetDir}" ]]
+# Keep the tempRecipeDir around because it could have been created by diff-guide-prepare
+if [[ ! -d "${tempRecipeDir}" ]]
 then
-  mkdir "${tempRulesetDir}" || exit 1
+  mkdir "${tempRecipeDir}" || exit 1
 # else
-#   # rm -rf "${tempRulesetDir}" || exit 1
+#   # rm -rf "${tempRecipeDir}" || exit 1
 fi
 
 
@@ -89,15 +89,15 @@ source ./books.txt || exit 1
 # Filter BOOK_CONFIGS to only contain the book you want to fetch
 for bookConfig in "${BOOK_CONFIGS[@]}"
 do
-  read -r bookConfigName rulesetConfigName uuid hostName basedOns <<< "${bookConfig}"
+  read -r bookConfigName recipeConfigName uuid hostName basedOns <<< "${bookConfig}"
 
-  if [[ "${rulesetName}" = "${rulesetConfigName}" ]]
+  if [[ "${recipeName}" = "${recipeConfigName}" ]]
   then
     # Actually copy the directories over (like common/,books/physics/)
     IFS=',' read -ra basedOnDirs <<< "$basedOns"
     for basedOnDirName in "${basedOnDirs[@]}"; do
       echo "==> Including ${sassDir}/${basedOnDirName}"
-      cp -R "${sassDir}/${basedOnDirName}" "${tempRulesetDir}/$(basename ${basedOnDirName})" || exit 1
+      cp -R "${sassDir}/${basedOnDirName}" "${tempRecipeDir}/$(basename ${basedOnDirName})" || exit 1
     done
     foundConfig=1
     break
@@ -106,16 +106,16 @@ done
 
 if [[ ! 1 -eq "${foundConfig}" ]]
 then
-  >&2 echo "ERROR: Could not find Book info for book named ${rulesetName}"
+  >&2 echo "ERROR: Could not find Book info for book named ${recipeName}"
   >&2 echo "check ./books.txt"
   exit 1
 fi
 
-cp -R "${bookDocumentationDir}" "${tempRulesetDir}" || exit 1
+cp -R "${bookDocumentationDir}" "${tempRecipeDir}" || exit 1
 
 
 # Find all the styleguide html files and convert them
-for snippetFileName in $(find "${tempRulesetDir}" -name "*.xhtml")
+for snippetFileName in $(find "${tempRecipeDir}" -name "*.xhtml")
 do
 
   if [[ ! "${snippetFileName}" =~ "-baked.xhtml" ]]
@@ -125,8 +125,8 @@ do
 
       >&2 echo "Generating temporary ${snippetFileName}-${bakedOrPreparedSuffix}.html"
       # commented because xmllint does not like html5 element names like <figure>
-      # ./script/bake-file ${rulesetName} ${snippetFileName} /dev/stdout | xmllint --html --format - > ${snippetFileName}-baked.xhtml
-      ./script/bake-file ${rulesetName} ${snippetFileName} ${snippetFileName}-temp1-${bakedOrPreparedSuffix}.xhtml --use-repeatable-ids  || exit 1
+      # ./script/bake-file ${recipeName} ${snippetFileName} /dev/stdout | xmllint --html --format - > ${snippetFileName}-baked.xhtml
+      ./script/bake-file ${recipeName} ${snippetFileName} ${snippetFileName}-temp1-${bakedOrPreparedSuffix}.xhtml --use-repeatable-ids  || exit 1
 
       # Construct an HTML file that contains both the raw and baked HTML
       # so it can be separated in the browser
@@ -150,11 +150,11 @@ then
   >&2 echo "==> Generating the style guide"
   # The CSS path is relative to the styleguide directory, hence `./guide.css`
   # Exclude parsing the output/*.css files by setting the --mask
-  $(npm bin)/kss-node --template ./js/openstax-kss-builder --verbose --homepage ${guideHomepageFile} --destination ${styleguideDir} --css ./guide.css --source ${tempRulesetDir} --mask '*.less|*.sass|*.scss|*.styl|*.stylus' > "${kssOutputFile}"  || exit 1
+  $(npm bin)/kss-node --template ./js/openstax-kss-builder --verbose --homepage ${guideHomepageFile} --destination ${styleguideDir} --css ./guide.css --source ${tempRecipeDir} --mask '*.less|*.sass|*.scss|*.styl|*.stylus' > "${kssOutputFile}"  || exit 1
 
   # Delete the temp files created above
   # >&2 echo "==> Deleting the baked example HTML files"
-  # for snippetFileName in $(find ./rulesets/books/ -name "*-${bakedOrPreparedSuffix}.xhtml")
+  # for snippetFileName in $(find ./recipes/books/ -name "*-${bakedOrPreparedSuffix}.xhtml")
   # do
   #   # echo "Removing temporary ${snippetFileName}"
   #   rm ${snippetFileName} || exit 1
@@ -174,7 +174,7 @@ then
   # Generate an HTML report (if genhtml is installed)
   if [[ -n "$(which genhtml)" ]]
   then
-    genhtml --quiet --output ./coverage/ $(find "${tempRulesetDir}" -name "*.lcov")
+    genhtml --quiet --output ./coverage/ $(find "${tempRecipeDir}" -name "*.lcov")
   fi
 
   >&2 echo "Guide is available at ${styleguideDir} . You can open it in a browser"
