camelCase vars in generate-guide

diff --git a/scripts/_convert-bookname-to-ruleset-name-and-uuid b/scripts/_convert-bookname-to-ruleset-name-and-uuid
--- a/scripts/_convert-bookname-to-ruleset-name-and-uuid
+++ b/scripts/_convert-bookname-to-ruleset-name-and-uuid
@@ -2,10 +2,10 @@
 set -e
 
 
-BOOK_NAME=$1
+bookName=$1
 BOOK_CONFIG_FILE="./books.txt"
 
-if [ -z "${BOOK_NAME}" ]
+if [ -z "${bookName}" ]
 then
   >&2 echo "This utility script converts a book name (like microecon)"
   >&2 echo "to the ruleset name the should be used to generate the book"
@@ -26,13 +26,13 @@ fi
 eval $(cat ${BOOK_CONFIG_FILE})
 
 
-# Pull out the ruleset name that matches the ${BOOK_NAME}
-RULESET_NAME=$(eval echo \${${BOOK_NAME}_ruleset_name})
-UUID=$(eval echo \${${BOOK_NAME}_uuid})
+# Pull out the ruleset name that matches the ${bookName}
+RULESET_NAME=$(eval echo \${${bookName}_ruleset_name})
+UUID=$(eval echo \${${bookName}_uuid})
 
 if [ -z "${RULESET_NAME}" ]
 then
-  >&2 echo "ERROR: could not find a ruleset_name for the book named ${BOOK_NAME}"
+  >&2 echo "ERROR: could not find a ruleset_name for the book named ${bookName}"
   >&2 echo "Please check the ${BOOK_CONFIG_FILE} file and make sure the entry exits"
   exit 1
 fi
diff --git a/scripts/bake-book b/scripts/bake-book
--- a/scripts/bake-book
+++ b/scripts/bake-book
@@ -2,24 +2,24 @@
 set -e
 
 
-BOOK_NAME=$1
+bookName=$1
 DEBUG_FLAG=$2
 
-RAW_PATH="./data/${BOOK_NAME}-raw.html"
-BAKED_PATH="./data/${BOOK_NAME}-baked.html"
+RAW_PATH="./data/${bookName}-raw.html"
+BAKED_PATH="./data/${bookName}-baked.html"
 
 # Check command line args
 
-if [ -z "${BOOK_NAME}" ]
+if [ -z "${bookName}" ]
 then
   >&2 echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'
   exit 1
 fi
 
-RULESET_NAME_AND_UUID=($(./scripts/_convert-bookname-to-ruleset-name-and-uuid ${BOOK_NAME}))
+RULESET_NAME_AND_UUID=($(./scripts/_convert-bookname-to-ruleset-name-and-uuid ${bookName}))
 RULESET_NAME=${RULESET_NAME_AND_UUID[0]}
-SASS_PATH="./books/rulesets/${RULESET_NAME}/book.scss"
-CSS_PATH="./books/rulesets/output/${RULESET_NAME}.css"
+sassFile="./books/rulesets/${RULESET_NAME}/book.scss"
+cssFile="./books/rulesets/output/${RULESET_NAME}.css"
 
 if [ ! -f "${RAW_PATH}" ]
 then
@@ -27,19 +27,19 @@ then
   exit 1
 fi
 
-if [ ! -f "${SASS_PATH}" ]
+if [ ! -f "${sassFile}" ]
 then
-  >&2 echo "ERROR: Could not find the raw SCSS file at ${SASS_PATH}"
+  >&2 echo "ERROR: Could not find the raw SCSS file at ${sassFile}"
   exit 1
 fi
 
 
->&2 echo "==> Compile SASS to CSS (${SASS_PATH})"
-bundle exec sass ${SASS_PATH} ${CSS_PATH}
+>&2 echo "==> Compile SASS to CSS (${sassFile})"
+bundle exec sass ${sassFile} ${cssFile}
 
 >&2 echo "==> Baking the book (may take a couple minutes)"
 >&2 echo "Specify additional commandline arguments like -d to this script if you want more debugging"
->&2 echo "Info: Baking ${RAW_PATH} to ${BAKED_PATH} using ${CSS_PATH}"
+>&2 echo "Info: Baking ${RAW_PATH} to ${BAKED_PATH} using ${cssFile}"
 
 # Remove the baked file if it exists
 [ -e "${BAKED_PATH}" ] && rm ${BAKED_PATH}
@@ -50,7 +50,7 @@ then
   . ./venv/bin/activate
 fi
 
-cnx-easybake ${DEBUG_FLAG} ${CSS_PATH} ${RAW_PATH} ${BAKED_PATH}
+cnx-easybake ${DEBUG_FLAG} ${cssFile} ${RAW_PATH} ${BAKED_PATH}
 
 # Validate the cooked file
 cnx-epub-validate-collated ${BAKED_PATH}
diff --git a/scripts/fetch-book b/scripts/fetch-book
--- a/scripts/fetch-book
+++ b/scripts/fetch-book
@@ -25,22 +25,22 @@ fi
 
 >&2 echo "Preparing to fetch book(s): ${BOOK_LIST}"
 
-for BOOK_NAME in ${BOOK_LIST}
+for bookName in ${BOOK_LIST}
 do
 
-  RULESET_NAME_AND_UUID=($(./scripts/_convert-bookname-to-ruleset-name-and-uuid ${BOOK_NAME}))
+  RULESET_NAME_AND_UUID=($(./scripts/_convert-bookname-to-ruleset-name-and-uuid ${bookName}))
   BOOK_UUID_AND_VER=${RULESET_NAME_AND_UUID[1]}
 
-  RAW_PATH="./data/${BOOK_NAME}-raw.html"
+  RAW_PATH="./data/${bookName}-raw.html"
 
   if [ -z "${BOOK_UUID_AND_VER}" ]
   then
-    >&2 echo "ERROR: Could not find Book UUID for book named ${BOOK_NAME}"
+    >&2 echo "ERROR: Could not find Book UUID for book named ${bookName}"
     exit 1
   fi
 
   >&2 echo "==> Generating an EPUB from the database and converting to a single HTML file (may take a minute)"
-  >&2 echo "Book name: ${BOOK_NAME} ${BOOK_UUID_AND_VER}"
+  >&2 echo "Book name: ${bookName} ${BOOK_UUID_AND_VER}"
 
   TEMP_EPUB_PATH="~/temp.intenral.epub"
   TEMP_HTML_PATH="~/temp.html"
diff --git a/scripts/generate-guide b/scripts/generate-guide
--- a/scripts/generate-guide
+++ b/scripts/generate-guide
@@ -1,27 +1,22 @@
 #!/bin/sh
 
-BOOK_NAME=$1
+bookName=$1
 
-# These are hardcoded only because phil was lazy and did not know how to parse filenames to get this data
-COMMON_GUIDE_TYPES="page.example page.exercise page.para page.note page.figure page.equation book.glossary page.section page.term page.table book.chapter book.page"
-SPECIFIC_GUIDE_TYPES="book.composite.practice page.note.chapter-objectives"
+sassDir='./books/'
+styleguideDir='./styleguide/'
+sassFile="${sassDir}/rulesets/${bookName}/book.scss"
+cssFile="${styleguideDir}/guide.css"
+bookCssFile="${sassDir}/rulesets/output/${bookName}.css"
+guideHomepageFile="./guide-homepage.md" # Relative to ${sassDir}/rulesets/
 
-
-SASS_DIR='./books/'
-STYLEGUIDE_DIR='./styleguide/'
-SASS_PATH="${SASS_DIR}/rulesets/${BOOK_NAME}/book.scss"
-CSS_PATH="${STYLEGUIDE_DIR}/guide.css"
-BOOK_CSS_PATH="${SASS_DIR}/rulesets/output/${BOOK_NAME}.css"
-HOMEPAGE_PATH="./guide-homepage.md" # Relative to ${SASS_DIR}/rulesets/
-
-TEMP_DIR="./tmp/"
-COMMON_DOCUMENTATION_DIR="./books/rulesets/common"
-BOOK_DOCUMENTATION_DIR="./books/rulesets/${BOOK_NAME}"
-KSS_OUTPUT_FILE="${TEMP_DIR}/kss-output.txt"
+tempDir="./tmp/"
+commonDocumentationDir="./books/rulesets/common"
+bookDocumentationDir="./books/rulesets/${bookName}"
+kssOutputFile="${tempDir}/kss-output.txt"
 
 # Check command line args
 
-if [ -z "${BOOK_NAME}" ]
+if [ -z "${bookName}" ]
 then
   >&2 echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'
   exit 1
@@ -30,72 +25,72 @@ fi
 
 
 >&2 echo "==> Compiling the guide.scss file"
-if [ ! -e ${STYLEGUIDE_DIR} ]
+if [ ! -e ${styleguideDir} ]
 then
-  mkdir ${STYLEGUIDE_DIR} || exit 1
+  mkdir ${styleguideDir} || exit 1
 fi
-bundle exec sass ${SASS_PATH} ${CSS_PATH} || exit 1
-bundle exec sass ${SASS_PATH} ${BOOK_CSS_PATH} || exit 1
+bundle exec sass ${sassFile} ${cssFile} || exit 1
+bundle exec sass ${sassFile} ${bookCssFile} || exit 1
 
 
 >&2 echo "==> Generating the baked example HTML files"
 
-# Create a temporary directory which contains the rulesets/common/ and rulesets/${BOOK_NAME} directories.
+# Create a temporary directory which contains the rulesets/common/ and rulesets/${bookName} directories.
 # This is because we want the styleguide to contain docs of all the common/ elements
 # and the book-specific elements, and kss only allows you to point to 1 directory
 # to look at all the SASS files.
-if [ -d "${TEMP_DIR}" ]
+if [ -d "${tempDir}" ]
 then
-  rm -rf "${TEMP_DIR}" || exit 1
+  rm -rf "${tempDir}" || exit 1
 fi
-mkdir "${TEMP_DIR}" || exit 1
-cp -R "${COMMON_DOCUMENTATION_DIR}" "${TEMP_DIR}" || exit 1
-cp -R "${BOOK_DOCUMENTATION_DIR}" "${TEMP_DIR}" || exit 1
+mkdir "${tempDir}" || exit 1
+cp -R "${commonDocumentationDir}" "${tempDir}" || exit 1
+cp -R "${bookDocumentationDir}" "${tempDir}" || exit 1
 
-for FILE_NAME in $(find "${TEMP_DIR}" -name "*.html")
+for snippetFileName in $(find "${tempDir}" -name "*.html")
 do
-  >&2 echo "Generating temporary ${FILE_NAME}-baked.html"
+  >&2 echo "Generating temporary ${snippetFileName}-baked.html"
   # commented because xmllint does not like html5 element names like <figure>
-  # ./scripts/bake-file ${BOOK_NAME} ${FILE_NAME} /dev/stdout | xmllint --html --format - > ${FILE_NAME}-baked.html
-  ./scripts/bake-file ${BOOK_NAME} ${FILE_NAME} ${FILE_NAME}-temp1-baked.html || exit 1
+  # ./scripts/bake-file ${bookName} ${snippetFileName} /dev/stdout | xmllint --html --format - > ${snippetFileName}-baked.html
+  ./scripts/bake-file ${bookName} ${snippetFileName} ${snippetFileName}-temp1-baked.html || exit 1
 
   # Construct an HTML file that contains both the raw and baked HTML
   # so it can be separated in the browser
   # (and so Phil does not have to completely rewrite kss becuase it assumes only 1 file for markup)
-  echo '<section class="-kss-autogen-guide-markup" data-kss-format="html-raw">' > ${FILE_NAME}-baked.html || exit 1
-  cat ${FILE_NAME} >> ${FILE_NAME}-baked.html || exit 1
-  echo '</section>' >> ${FILE_NAME}-baked.html || exit 1
-  echo '<section class="-kss-autogen-guide-markup" data-kss-format="html-baked">' >> ${FILE_NAME}-baked.html || exit 1
-  cat ${FILE_NAME}-temp1-baked.html >> ${FILE_NAME}-baked.html || exit 1
-  echo '</section>' >> ${FILE_NAME}-baked.html || exit 1
+  echo '<section class="-kss-autogen-guide-markup" data-kss-format="html-raw">' > ${snippetFileName}-baked.html || exit 1
+  cat ${snippetFileName} >> ${snippetFileName}-baked.html || exit 1
+  echo '</section>' >> ${snippetFileName}-baked.html || exit 1
+  echo '<section class="-kss-autogen-guide-markup" data-kss-format="html-baked">' >> ${snippetFileName}-baked.html || exit 1
+  cat ${snippetFileName}-temp1-baked.html >> ${snippetFileName}-baked.html || exit 1
+  echo '</section>' >> ${snippetFileName}-baked.html || exit 1
 
-  rm ${FILE_NAME}-temp1-baked.html || exit 1
+  rm ${snippetFileName}-temp1-baked.html || exit 1
 done
 
 
 >&2 echo "==> Generating the style guide"
 # The CSS path is relative to the styleguide directory, hence `./guide.css`
 # Exclude parsing the output/*.css files by setting the --mask
-$(npm bin)/kss-node --template ./js/openstax-kss-builder --verbose --homepage ${HOMEPAGE_PATH} --destination ${STYLEGUIDE_DIR} --css ./guide.css --source ${TEMP_DIR} --mask '*.less|*.sass|*.scss|*.styl|*.stylus' > "${KSS_OUTPUT_FILE}"  || exit 1
+$(npm bin)/kss-node --template ./js/openstax-kss-builder --verbose --homepage ${guideHomepageFile} --destination ${styleguideDir} --css ./guide.css --source ${tempDir} --mask '*.less|*.sass|*.scss|*.styl|*.stylus' > "${kssOutputFile}"  || exit 1
 
 
 # Delete the temp files created above
 >&2 echo "==> Deleting the baked example HTML files"
-for FILE_NAME in $(find ./books/rulesets/ -name "*-baked.html")
+for snippetFileName in $(find ./books/rulesets/ -name "*-baked.html")
 do
-  # echo "Removing temporary ${FILE_NAME}"
-  rm ${FILE_NAME} || exit 1
+  # echo "Removing temporary ${snippetFileName}"
+  rm ${snippetFileName} || exit 1
 done
 
 # HACK: KSS-node does not error if an HTML file is missing. Instead, it prints out a warning.
 # So, check the output of kss to see if any errors were reported.
-MISSING_FILES=$(cat "${KSS_OUTPUT_FILE}" | grep 'NOT FOUND!' )
-if [ -n "${MISSING_FILES}" ]
+missingFiles=$(cat "${kssOutputFile}" | grep 'NOT FOUND!' )
+if [ -n "${missingFiles}" ]
 then
   >&2 echo "ERROR: Some HTML files were missing:"
-  >&2 echo "${MISSING_FILES}"
-  >&2 echo "Check ${KSS_OUTPUT_FILE} for more details"
+  >&2 echo "${missingFiles}"
+  >&2 echo "Check ${kssOutputFile} for more details"
   exit 1
 fi
 
->&2 echo "Guide is available at ${STYLEGUIDE_DIR} . You can open it in a browser"
+>&2 echo "Guide is available at ${styleguideDir} . You can open it in a browser"
diff --git a/scripts/report-book-coverage b/scripts/report-book-coverage
--- a/scripts/report-book-coverage
+++ b/scripts/report-book-coverage
@@ -21,23 +21,23 @@ else
   BOOK_LIST="${ARG1}"
 fi
 
-for BOOK_NAME in ${BOOK_LIST}
+for bookName in ${BOOK_LIST}
 do
 
-  RAW_PATH="./data/${BOOK_NAME}-raw.html"
-  LCOV_PATH="./data/${BOOK_NAME}.lcov"
+  RAW_PATH="./data/${bookName}-raw.html"
+  LCOV_PATH="./data/${bookName}.lcov"
 
   if [ -f "${RAW_PATH}" ]
   then
 
-    RULESET_NAME_AND_UUID=($(./scripts/_convert-bookname-to-ruleset-name-and-uuid ${BOOK_NAME}))
+    RULESET_NAME_AND_UUID=($(./scripts/_convert-bookname-to-ruleset-name-and-uuid ${bookName}))
     RULESET_NAME=${RULESET_NAME_AND_UUID[0]}
 
-    CSS_PATH="./books/rulesets/output/${RULESET_NAME}.css"
+    cssFile="./books/rulesets/output/${RULESET_NAME}.css"
 
-    if [ ! -f "${CSS_PATH}" ]
+    if [ ! -f "${cssFile}" ]
     then
-      >&2 echo "ERROR: CSS File missing at ${CSS_PATH}"
+      >&2 echo "ERROR: CSS File missing at ${cssFile}"
       exit 1
     fi
 
@@ -47,19 +47,19 @@ do
 
     if [ "${ARG1}" == "--all" ]
     then
-      >&2 echo "Generating coverage for ${BOOK_NAME} in ${LCOV_PATH}"
+      >&2 echo "Generating coverage for ${bookName} in ${LCOV_PATH}"
     else
       >&2 echo "Coverage is being generated. To see an HTML version, run the following:"
       >&2 echo "genhtml ${LCOV_PATH} --output-directory ./coverage"
       >&2 echo "Note: to run this you may need to install genhtml. In OSX it is 'brew install lcov'"
     fi
 
-    ./node_modules/.bin/css-coverage --css ${CSS_PATH} --html ${RAW_PATH} --lcov ${LCOV_PATH} ${DEBUG_FLAG1} ${DEBUG_FLAG2}
+    ./node_modules/.bin/css-coverage --css ${cssFile} --html ${RAW_PATH} --lcov ${LCOV_PATH} ${DEBUG_FLAG1} ${DEBUG_FLAG2}
 
   else
     if [ "${ARG1}" == "--all" ]
     then
-      >&2 echo "WARNING: Skipping ${BOOK_NAME} because HTML File is missing at ${RAW_PATH}"
+      >&2 echo "WARNING: Skipping ${bookName} because HTML File is missing at ${RAW_PATH}"
     else
       >&2 echo "ERROR: HTML File missing at ${RAW_PATH}"
       exit 1
