Add config file for book UUIDs and which ruleset they map to
to keep everyone in-sync, make it easier to fetch updates, and make it
easier to bake a book

diff --git a/scripts/bake-book b/scripts/bake-book
--- a/scripts/bake-book
+++ b/scripts/bake-book
@@ -5,8 +5,6 @@ set -e
 BOOK_NAME=$1
 DEBUG_FLAG=$2
 
-SASS_PATH="./books/rulesets/${BOOK_NAME}.scss"
-CSS_PATH="./books/rulesets/output/${BOOK_NAME}.css"
 RAW_PATH="./data/${BOOK_NAME}-raw.html"
 COOKED_PATH="./data/${BOOK_NAME}-cooked.html"
 
@@ -14,27 +12,33 @@ COOKED_PATH="./data/${BOOK_NAME}-cooked.html"
 
 if [ -z "${BOOK_NAME}" ]
 then
-  echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'
+  >&2 echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'
   exit 1
 fi
 
+RULESET_NAME_AND_UUID=($(./scripts/_convert-bookname-to-ruleset-name-and-uuid ${BOOK_NAME}))
+RULESET_NAME=${RULESET_NAME_AND_UUID[0]}
+SASS_PATH="./books/rulesets/${RULESET_NAME}.scss"
+CSS_PATH="./books/rulesets/output/${RULESET_NAME}.css"
+
 if [ ! -f "${RAW_PATH}" ]
 then
-  echo 'ERROR: Could not find the raw HTML file. Have you run fetch-book yet?'
+  >&2 echo 'ERROR: Could not find the raw HTML file. Have you run fetch-book yet?'
   exit 1
 fi
 
 if [ ! -f "${SASS_PATH}" ]
 then
-  echo "ERROR: Could not find the raw SCSS file at ${SASS_PATH}"
+  >&2 echo "ERROR: Could not find the raw SCSS file at ${SASS_PATH}"
   exit 1
 fi
 
 
-echo "Step 1/2: Compile SASS to CSS"
+>&2 echo "Step 1/2: Compile SASS to CSS (${SASS_PATH})"
 sass ${SASS_PATH} ${CSS_PATH}
 
-echo "Step 2/2: Baking the book (may take a couple minutes). specify additional commandline arguments like -d to this script if you want more debugging"
+>&2 echo "Step 2/2: Baking the book (may take a couple minutes). specify additional commandline arguments like -d to this script if you want more debugging"
+>&2 echo "Info: Baking ${RAW_PATH} to ${COOKED_PATH} using ${CSS_PATH}"
 
 # Remove the cooked file if it exists
 [ -e "${COOKED_PATH}" ] && rm ${COOKED_PATH}
diff --git a/scripts/fetch-book b/scripts/fetch-book
--- a/scripts/fetch-book
+++ b/scripts/fetch-book
@@ -7,7 +7,9 @@ set -e
 HOST='cte-cnx-dev.cnx.org'
 
 BOOK_NAME=$1
-BOOK_UUID_AND_VER=$2
+
+RULESET_NAME_AND_UUID=($(./scripts/_convert-bookname-to-ruleset-name-and-uuid ${BOOK_NAME}))
+BOOK_UUID_AND_VER=${RULESET_NAME_AND_UUID[1]}
 
 RAW_PATH="./data/${BOOK_NAME}-raw.html"
 
@@ -15,18 +17,18 @@ RAW_PATH="./data/${BOOK_NAME}-raw.html"
 
 if [ -z "${BOOK_NAME}" ]
 then
-  echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'
+  >&2 echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'
   exit 1
 fi
 
 if [ -z "${BOOK_UUID_AND_VER}" ]
 then
-  echo 'ERROR: Argument Missing. You must specify the UUID of the book to download as the 2nd argument. For example: 30189442-6998-4686-ac05-ed152b91b9de@19.2'
+  >&2 echo 'ERROR: Argument Missing. You must specify the UUID of the book to download as the 2nd argument. For example: 30189442-6998-4686-ac05-ed152b91b9de@19.2'
   exit 1
 fi
 
 
-echo "Step 1/2: Generating an EPUB from the database and converting to a single HTML file (may take a minute)"
+>&2 echo "Step 1/2: Generating an EPUB from the database and converting to a single HTML file (may take a minute)"
 
 TEMP_EPUB_PATH="~/temp.intenral.epub"
 TEMP_HTML_PATH="~/temp.html"
@@ -40,7 +42,7 @@ CMD="${RM_TEMP_EPUB_CMD}; ${RM_TEMP_HTML_CMD}; ${GENERATE_EPUB_CMD} && ${GENERAT
 
 ssh ${USER}@${HOST} ${CMD}
 
-echo "Step 2/2: Copying HTML file from server to local machine"
+>&2 echo "Step 2/2: Copying HTML file from server to local machine"
 scp ${USER}@${HOST}:${TEMP_HTML_PATH} ${RAW_PATH}
 
-echo "Fetch is done. File is available at ${RAW_PATH}"
+>&2 echo "Fetch is done. File is available at ${RAW_PATH}"
