improve the structure of the books.txt config

diff --git a/scripts/bake-book b/scripts/bake-book
--- a/scripts/bake-book
+++ b/scripts/bake-book
@@ -1,56 +1,84 @@
-#!/bin/sh
+#!/bin/bash
 set -e
 
 
-bookName=$1
+arg1=$1
 debugFlag=$2
-
-rawFile="./data/${bookName}-raw.html"
-bakedFile="./data/${bookName}-baked.html"
 
 # Check command line args
 
-if [ -z "${bookName}" ]
+if [ -z "${arg1}" ]
 then
-  >&2 echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'
-  exit 1
-fi
-
-rulesetNameAndUuid=($(./scripts/_convert-bookname-to-ruleset-name-and-uuid ${bookName}))
-rulesetName=${rulesetNameAndUuid[0]}
-sassFile="./books/rulesets/${rulesetName}/book.scss"
-cssFile="./books/rulesets/output/${rulesetName}.css"
-
-if [ ! -f "${rawFile}" ]
-then
-  >&2 echo 'ERROR: Could not find the raw HTML file. Have you run fetch-book yet?'
-  exit 1
-fi
-
-if [ ! -f "${sassFile}" ]
-then
-  >&2 echo "ERROR: Could not find the raw SCSS file at ${sassFile}"
+  >&2 echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument (or --all). For example: physics'
+  >&2 echo "You can specify additional commandline arguments like -d to this script if you want more debugging"
   exit 1
 fi
 
 
->&2 echo "==> Compile SASS to CSS (${sassFile})"
-bundle exec sass ${sassFile} ${cssFile}
+# Pull in the BOOK_CONFIGS
+source ./books.txt || exit 1
 
->&2 echo "==> Baking the book (may take a couple minutes)"
->&2 echo "Specify additional commandline arguments like -d to this script if you want more debugging"
->&2 echo "Info: Baking ${rawFile} to ${bakedFile} using ${cssFile}"
-
-# Remove the baked file if it exists
-[ -e "${bakedFile}" ] && rm ${bakedFile}
-
-# Activate the venv if not running Travis or already in a virtualenv
-if [[ ! "${CI}" = "true" && -z "${VIRTUAL_ENV}" ]]
+if [ ! "${arg1}" == "--all" ]
 then
-  source ./venv/bin/activate
+  # Filter BOOK_CONFIGS to only contain the book you want to fetch
+  for bookConfig in "${BOOK_CONFIGS[@]}"
+  do
+    read -r bookConfigName rulesetName uuid _ <<< "${bookConfig}"
+
+    if [[ "${arg1}" = "${bookConfigName}" ]]
+    then
+      BOOK_CONFIGS=("${bookConfigName} ${rulesetName} ${uuid}")
+      foundConfig=1
+      break
+    fi
+  done
+
+  if [[ ! 1 -eq "${foundConfig}" ]]
+  then
+    >&2 echo "ERROR: Could not find Book info for book named ${arg1}"
+    >&2 echo "check ./books.txt"
+    exit 1
+  fi
 fi
 
-cnx-easybake ${debugFlag} ${cssFile} ${rawFile} ${bakedFile}
 
-# Validate the cooked file
-cnx-epub-validate-collated ${bakedFile}
+./scripts/compile-books || exit 1
+
+for bookConfig in "${BOOK_CONFIGS[@]}"
+do
+  read -r bookName rulesetName uuid _ <<< "${bookConfig}"
+
+  rawFile="./data/${bookName}-raw.html"
+  bakedFile="./data/${bookName}-baked.html"
+  sassFile="./books/rulesets/${rulesetName}/book.scss"
+  cssFile="./books/rulesets/output/${rulesetName}.css"
+
+  if [ ! -f "${rawFile}" ]
+  then
+    >&2 echo 'ERROR: Could not find the raw HTML file. Have you run fetch-book yet?'
+    exit 1
+  fi
+
+  if [ ! -f "${sassFile}" ]
+  then
+    >&2 echo "ERROR: Could not find the raw SCSS file at ${sassFile}"
+    exit 1
+  fi
+
+
+  >&2 echo "==> Baking ${rawFile} using ${rulesetName} (may take a few minutes)"
+
+  # Remove the baked file if it exists
+  [ -e "${bakedFile}" ] && rm ${bakedFile}
+
+  # Activate the venv if not running Travis or already in a virtualenv
+  if [[ ! "${CI}" = "true" && -z "${VIRTUAL_ENV}" ]]
+  then
+    source ./venv/bin/activate
+  fi
+
+  cnx-easybake ${debugFlag} ${cssFile} ${rawFile} ${bakedFile}
+
+  # Validate the cooked file
+  cnx-epub-validate-collated ${bakedFile}
+done
diff --git a/scripts/fetch-book b/scripts/fetch-book
--- a/scripts/fetch-book
+++ b/scripts/fetch-book
@@ -16,37 +16,47 @@ then
   exit 1
 fi
 
-if [ "${arg1}" == "--all" ]
+# Pull in the BOOK_CONFIGS
+source ./books.txt || exit 1
+
+if [ ! "${arg1}" == "--all" ]
 then
-  source ./books.txt
-else
-  BOOK_LIST="${arg1}"
-fi
+  # Filter BOOK_CONFIGS to only contain the book you want to fetch
+  for bookConfig in "${BOOK_CONFIGS[@]}"
+  do
+    read -r bookConfigName rulesetName uuid _ <<< "${bookConfig}"
 
->&2 echo "Preparing to fetch book(s): ${BOOK_LIST}"
+    if [[ "${arg1}" = "${bookConfigName}" ]]
+    then
+      BOOK_CONFIGS=("${bookConfigName} ${rulesetName} ${uuid}")
+      foundConfig=1
+      break
+    fi
+  done
 
-for bookName in ${BOOK_LIST}
-do
-
-  rulesetNameAndUuid=($(./scripts/_convert-bookname-to-ruleset-name-and-uuid ${bookName}))
-  bookUuidAndVer=${rulesetNameAndUuid[1]}
-  rawFile="./data/${bookName}-raw.html"
-
-  if [ -z "${bookUuidAndVer}" ]
+  if [[ ! 1 -eq "${foundConfig}" ]]
   then
-    >&2 echo "ERROR: Could not find Book UUID for book named ${bookName}"
+    >&2 echo "ERROR: Could not find Book info for book named ${arg1}"
+    >&2 echo "check ./books.txt"
     exit 1
   fi
+fi
 
-  >&2 echo "==> Generating an EPUB from the database and converting to a single HTML file (may take a minute)"
-  >&2 echo "Book name: ${bookName} ${bookUuidAndVer}"
+for bookConfig in "${BOOK_CONFIGS[@]}"
+do
+  read -r bookName rulesetName uuid _ <<< "${bookConfig}"
+  rawFile="./data/${bookName}-raw.html"
+
+  >&2 echo "==> Fetching ${bookName}"
+  >&2 echo "generating an EPUB from the database and converting to a single HTML file"
+  >&2 echo "(may take a minute)..."
 
   tempEpubFile="~/temp.intenral.epub"
   tempHtmlFile="~/temp.html"
 
   rmTempEpubCmd="[ -e ${tempEpubFile} ] && rm ${tempEpubFile}"
   rmTempHtmlCmd="[ -e ${tempHtmlFile} ] && rm ${tempHtmlFile}"
-  generateEpubCmd="/var/cnx/venvs/publishing/bin/cnx-archive-export_epub /etc/cnx/publishing/app.ini ${bookUuidAndVer} ${tempEpubFile}"
+  generateEpubCmd="/var/cnx/venvs/publishing/bin/cnx-archive-export_epub /etc/cnx/publishing/app.ini ${uuid} ${tempEpubFile}"
   generateHtmlCmd="/var/cnx/venvs/publishing/bin/cnx-epub-single_html ${tempEpubFile} > ${tempHtmlFile}"
 
   commands="${rmTempEpubCmd}; ${rmTempHtmlCmd}; ${generateEpubCmd} && ${generateHtmlCmd}"
diff --git a/scripts/report-book-coverage b/scripts/report-book-coverage
--- a/scripts/report-book-coverage
+++ b/scripts/report-book-coverage
@@ -1,5 +1,4 @@
-#!/bin/sh
-set -e
+#!/bin/bash
 
 
 arg1=$1
@@ -14,24 +13,41 @@ then
   exit 1
 fi
 
-if [ "${arg1}" == "--all" ]
+# Pull in the BOOK_CONFIGS
+source ./books.txt || exit 1
+
+if [ ! "${arg1}" == "--all" ]
 then
-  source ./books.txt
-else
-  BOOK_LIST="${arg1}"
+  # Filter BOOK_CONFIGS to only contain the book you want to fetch
+  for bookConfig in "${BOOK_CONFIGS[@]}"
+  do
+    read -r bookConfigName rulesetName uuid _ <<< "${bookConfig}"
+
+    if [[ "${arg1}" = "${bookConfigName}" ]]
+    then
+      BOOK_CONFIGS=("${bookConfigName} ${rulesetName} ${uuid}")
+      foundConfig=1
+      break
+    fi
+  done
+
+  if [[ ! 1 -eq "${foundConfig}" ]]
+  then
+    >&2 echo "ERROR: Could not find Book info for book named ${arg1}"
+    >&2 echo "check ./books.txt"
+    exit 1
+  fi
 fi
 
-for bookName in ${BOOK_LIST}
+for bookConfig in "${BOOK_CONFIGS[@]}"
 do
+  read -r bookName rulesetName uuid _ <<< "${bookConfig}"
 
   rawFile="./data/${bookName}-raw.html"
   lcovFile="./data/${bookName}.lcov"
 
   if [ -f "${rawFile}" ]
   then
-
-    rulesetNameAndUuid=($(./scripts/_convert-bookname-to-ruleset-name-and-uuid ${bookName}))
-    rulesetName=${rulesetNameAndUuid[0]}
 
     cssFile="./books/rulesets/output/${rulesetName}.css"
 
@@ -45,16 +61,8 @@ do
     # a non-zero exit status if there are unused selectors
     # and the `set -e` at the top of this script will exit at that point
 
-    if [ "${arg1}" == "--all" ]
-    then
-      >&2 echo "Generating coverage for ${bookName} in ${lcovFile}"
-    else
-      >&2 echo "Coverage is being generated. To see an HTML version, run the following:"
-      >&2 echo "genhtml ${lcovFile} --output-directory ./coverage"
-      >&2 echo "Note: to run this you may need to install genhtml. In OSX it is 'brew install lcov'"
-    fi
-
-    ./node_modules/.bin/css-coverage --css ${cssFile} --html ${rawFile} --lcov ${lcovFile} ${debugFlag1} ${debugFlag2}
+    >&2 echo "==> Generating coverage for ${bookName} in ${lcovFile}"
+    $(npm bin)/css-coverage --css ${cssFile} --html ${rawFile} --lcov ${lcovFile} ${debugFlag1} ${debugFlag2}
 
   else
     if [ "${arg1}" == "--all" ]
@@ -68,9 +76,20 @@ do
 
 done
 
-if [ "${arg1}" == "--all" ]
+# Generate the HTML coverage report if genhtml is installed
+if [[ -n "$(genhtml --version)" ]]
 then
-  >&2 echo "Generated coverage for ${BOOK_LIST}. To see an HTML version, run the following:"
-  >&2 echo "genhtml ./data/*.lcov --output-directory ./coverage"
-  >&2 echo "Note: to run this you may need to install genhtml. In OSX it is 'brew install lcov'"
+
+  if [ "${arg1}" == "--all" ]
+  then
+    genhtml ./data/*.lcov --output-directory ./coverage || exit 1
+  else
+    genhtml ${lcovFile} --output-directory ./coverage || exit 1
+  fi
+
+  >&2 echo "Generated HTML coverage report in ./coverage/"
+
+else
+  >&2 echo "./data/*.lcov file(s) are generated."
+  >&2 echo "Install genhtml to create an HTML coverage report."
 fi
