fixup! add script to retrigger baking a book remotely

diff --git a/scripts/bake-book-remote b/scripts/bake-book-remote
--- a/scripts/bake-book-remote
+++ b/scripts/bake-book-remote
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 set -e
 
 # This re-bakes a book on ${HOST} (or all books if using the --all argument)
@@ -35,13 +35,11 @@ if [ "${ARG1}" == "--all" ]
 then
   >&2 echo "--all is not a valid option because you have to specify a version for the book you want to rebake"
   exit 1
+else
+  BOOK_LIST="${ARG1}"
 fi
 
-if [ -z "${BOOK_VERSION}" ]
-then
-  >&2 echo 'ERROR: Argument Missing. You must specify the book version as the 2nd argument for what you want to cook (I know, it is annoying)'
-  exit 1
-fi
+. ./bin/activate
 
 
 >&2 echo "Preparing to fetch book(s): ${BOOK_LIST}"
@@ -61,6 +59,13 @@ do
     exit 1
   fi
 
+  if [ -z "${BOOK_VERSION}" ]
+  then
+    >&2 echo 'ERROR: Argument Missing. You must specify the book version as the 2nd argument for what you want to cook (I know, it is annoying)'
+    >&2 echo "You can visit http://${HOST}/contents/${BOOK_UUID_AND_VER} to get the version number"
+    exit 1
+  fi
+
   >&2 echo "Baking book ${BOOK_NAME} ${BOOK_UUID_AND_VER} on ${HOST}"
 
   TEMP_CSS_PATH="~/temp.css"
@@ -68,13 +73,13 @@ do
   >&2 echo "Step 1/3: Copying CSS file from local machine to server"
   scp ${CSS_PATH} ${USER}@${HOST}:${TEMP_CSS_PATH}
 
-  >&2 echo "Step 2/3: Baking the book (may take a minute)"
+  >&2 echo "Step 2/3: Injecting the css file into the book as ruleset.css"
 
-  BUILD_BOOK_CMD="/var/cnx/venvs/archive/bin/cnx-archive-inject_resource --resource-filename \"ruleset.css\" --media-type \"text/css\" /etc/cnx/archive/app.ini \"${BOOK_UUID_AND_VER}\" ${TEMP_CSS_PATH}"
-  INVOKE_COLLATION_CMD="python -c 'import requests; resp = requests.post(\"http://${HOST}:6543/contents/${BOOK_UUID_AND_VER}@${BOOK_VERSION}/collate-content\", headers={\"x-api-key\": \"cte-dev--sprint-6.7\"}); print(resp)'"
-  CMD="${BUILD_BOOK_CMD} && ${INVOKE_COLLATION_CMD}"
+  BUILD_BOOK_CMD="/var/cnx/venvs/archive/bin/cnx-archive-inject_resource --resource-filename \"ruleset.css\" --media-type \"text/css\" /etc/cnx/archive/app.ini \"${BOOK_UUID_AND_VER}@${BOOK_VERSION}\" ${TEMP_CSS_PATH}"
+  ssh ${USER}@${HOST} ${BUILD_BOOK_CMD}
 
-  ssh ${USER}@${HOST} ${CMD}
+  >&2 echo "Step 3/3: Re-baking the book (may take a couple minutes)"
+  python -c "import requests; resp = requests.post('http://${HOST}:6543/contents/${BOOK_UUID_AND_VER}@${BOOK_VERSION}/collate-content', headers={'x-api-key': 'cte-dev--sprint-6.7'}); print(resp)"
 
   >&2 echo "Build has hopefully been triggered."
 
