show helpful error when rbenv is not properly installed

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -23,18 +23,28 @@ if [ ! "${CI}" = "true" ] && [ -f ".ruby-version" ] && [ -z "$(rbenv version-nam
   rbenv install --skip-existing
 fi
 
->&2 echo "Using ruby via rbenv:"
-rbenv version
-
 which bundle >/dev/null 2>&1  || {
   >&2 echo "==> Installing Ruby Bundler gem…"
   rbenv version
-  gem install bundler
+  gem install bundler || {
+    >&2 echo ''
+    >&2 echo ''
+    >&2 echo '--------------- Error -------------'
+    >&2 echo 'Unable to install the bundler.'
+    >&2 echo 'You may need to add the following to ~/.bash_profile :'
+    >&2 echo ''
+    >&2 echo 'eval "$(rbenv init -)"'
+    >&2 echo ''
+    >&2 echo 'Doing this will require restarting your terminal'
+    >&2 echo 'or running "source ~/.bash_profile"'
+    exit 1
+  }
   rbenv rehash
 }
 
 if [ -f "Gemfile" ]; then
   >&2 echo "==> Installing gem dependencies…"
+  which bundle
   bundle check --path vendor/gems >/dev/null 2>&1  || {
     bundle install --path vendor/gems --quiet --without production
   }
