fallback to globally installed sass
when rbenv is not found

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -17,13 +17,22 @@ if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
   }
 fi
 
+
+>&2 echo "==> Installing Node package dependencies"
+>&2 echo "Using node: $(node --version)"
+>&2 echo "Using npm: $(npm --version)"
+npm install || exit 1
+
 # Note: Skip rbenv for Travis because it already has ruby
 if [ ! "${CI}" = "true" ] && [ -f ".ruby-version" ]; then
   if [[ -n $(which rbenv) ]]; then
 
     if [ -z "$(rbenv version-name 2>/dev/null)" ]; then
       >&2 echo "==> Installing Ruby…"
-      rbenv install --skip-existing
+      rbenv install --skip-existing || {
+        echo "WARNING: 'rbenv install' errored. I am assuming you know what you are doing (and have sass installed locally) so continuing"
+        exit 0
+      }
     fi
   else
     >&2 echo "WARNING: Skipping rbenv. Using local ruby"
@@ -54,9 +63,3 @@ if [ -f "Gemfile" ]; then
     bundle install --path vendor/gems --quiet --without production
   }
 fi
-
-
->&2 echo "==> Installing Node package dependencies"
->&2 echo "Using node: $(node --version)"
->&2 echo "Using npm: $(npm --version)"
-npm install || exit 1
diff --git a/scripts/generate-guide b/scripts/generate-guide
--- a/scripts/generate-guide
+++ b/scripts/generate-guide
@@ -39,8 +39,23 @@ if [ ! -e ${styleguideDir} ]
 then
   mkdir -p ${styleguideDir} || exit 1
 fi
-bundle exec sass ${sassFile} ${cssFile} || exit 1
-bundle exec sass ${sassFile} ${bookCssFile} || exit 1
+
+
+# Try running sass locally (using rbenv). If that does not work then try it globally
+if [[ $(bundle exec sass --version) ]]
+then
+  sassBin="bundle exec sass"
+elif [[ $(sass --version) ]]
+then
+  >&2 echo "WARNING: Using global sass"
+  sassBin="sass"
+else
+  >&2 echo "ERROR: Could not find sass executable"
+  exit 1
+fi
+
+${sassBin} ${sassFile} ${cssFile} || exit 1
+${sassBin} ${sassFile} ${bookCssFile} || exit 1
 
 
 >&2 echo "==> Generating the baked example HTML files"
