travis: Skip installing bundler because you don't need it

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -18,29 +18,31 @@ if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
 fi
 
 # Note: Skip rbenv for Travis because it already has ruby
-if [ ! "${CI}" = "true" ] && [ -f ".ruby-version" ] && [ -z "$(rbenv version-name 2>/dev/null)" ]; then
-  >&2 echo "==> Installing Ruby…"
-  rbenv install --skip-existing
-fi
+if [ ! "${CI}" = "true" ] && [ -f ".ruby-version" ]; then
+  if [ -z "$(rbenv version-name 2>/dev/null)" ]; then
+    >&2 echo "==> Installing Ruby…"
+    rbenv install --skip-existing
+  fi
 
-which bundle >/dev/null 2>&1  || {
-  >&2 echo "==> Installing Ruby Bundler gem…"
-  rbenv version
-  gem install bundler || {
-    >&2 echo ''
-    >&2 echo ''
-    >&2 echo '--------------- Error -------------'
-    >&2 echo 'Unable to install the bundler.'
-    >&2 echo 'You may need to add the following to ~/.bash_profile :'
-    >&2 echo ''
-    >&2 echo 'eval "$(rbenv init -)"'
-    >&2 echo ''
-    >&2 echo 'Doing this will require restarting your terminal'
-    >&2 echo 'or running "source ~/.bash_profile"'
-    exit 1
+  which bundle >/dev/null 2>&1  || {
+    >&2 echo "==> Installing Ruby Bundler gem…"
+    rbenv version
+    gem install bundler || {
+      >&2 echo ''
+      >&2 echo ''
+      >&2 echo '--------------- Error -------------'
+      >&2 echo 'Unable to install the bundler.'
+      >&2 echo 'You may need to add the following to ~/.bash_profile :'
+      >&2 echo ''
+      >&2 echo 'eval "$(rbenv init -)"'
+      >&2 echo ''
+      >&2 echo 'Doing this will require restarting your terminal'
+      >&2 echo 'or running "source ~/.bash_profile"'
+      exit 1
+    }
+    rbenv rehash
   }
-  rbenv rehash
-}
+fi
 
 if [ -f "Gemfile" ]; then
   >&2 echo "==> Installing gem dependencies…"
