:art: clean up log messages and only show message once

diff --git a/scripts/compile-books b/scripts/compile-books
--- a/scripts/compile-books
+++ b/scripts/compile-books
@@ -14,6 +14,19 @@ then
   RULESET_NAMES=(${arg1})
 fi
 
+# Try running sass locally (using rbenv). If that does not work then try it globally
+if [[ $(bundle exec sass --version) ]]
+then
+  sassBin="bundle exec sass"
+elif [[ $(sass --version) ]]
+then
+  >&2 echo "INFO: Using system-installed $(sass --version)"
+  sassBin="sass"
+else
+  >&2 echo "ERROR: Could not find sass executable"
+  exit 1
+fi
+
 
 for rulesetName in "${RULESET_NAMES[@]}"
 do
@@ -23,17 +36,5 @@ do
 
   >&2 echo "==> Generating ${cssFile}"
 
-  # Try running sass locally (using rbenv). If that does not work then try it globally
-  if [[ $(bundle exec sass --version) ]]
-  then
-    sassBin="bundle exec sass"
-  elif [[ $(sass --version) ]]
-  then
-    >&2 echo "WARNING: Using global sass"
-    sassBin="sass"
-  else
-    >&2 echo "ERROR: Could not find sass executable"
-    exit 1
-  fi
   ${sassBin} ${sassFile} ${cssFile} || exit 1
 done
